// JavaScript Document
window.doodle={};doodle.utils={};doodle.geom={};doodle.events={};doodle.filters={};(function(){var a=[],f=function(){var d=a.length,e=0;if(d>0){for(;e<d;e++)a[e](doodle);a.length=0}},d=function(){f();document.removeEventListener("DOMContentLoaded",d,!1)};doodle.ready=function(d){a.push(d);document.readyState==="complete"&&f()};document.readyState!=="complete"&&(document.addEventListener?document.addEventListener("DOMContentLoaded",d,!1):console.error("document.addEventListener not supported."))})();
if(typeof Function.prototype.bind!=="function")Function.prototype.bind=function(a){var f=this;return function(){return f.apply(a,arguments)}};
(function(){Object.defineProperties(doodle.utils,{hex_to_rgb:{enumerable:!0,writable:!1,configurable:!1,value:function(a){typeof a==="string"&&(a=a[0]==="#"?a.slice(1):a,a=window.parseInt(a,16));return[a>>16&255,a>>8&255,a&255]}},hex_to_rgb_str:{enumerable:!0,writable:!1,configurable:!1,value:function(a,f){var d=doodle.utils,f=f===void 0?1:f,a=d.hex_to_rgb(a);return d.rgb_to_rgb_str(a[0],a[1],a[2],f)}},rgb_str_to_hex:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var f=doodle.utils,
a=f.rgb_str_to_rgb(a);return f.rgb_to_hex(window.parseInt(a[0],10),window.parseInt(a[1],10),window.parseInt(a[2],10))}},rgb_str_to_rgb:{enumerable:!0,writable:!1,configurable:!1,value:function(){var a=/^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,?(.*)\)$/;return function(f){var f=f.trim().match(a),d=[window.parseInt(f[1],10),window.parseInt(f[2],10),window.parseInt(f[3],10)],f=window.parseFloat(f[4]);typeof f==="number"&&!window.isNaN(f)&&d.push(f);return d}}()},rgb_to_hex:{enumerable:!0,
writable:!1,configurable:!1,value:function(a,f,d){a=(d|f<<8|a<<16).toString(16);return"#"+String("000000"+a).slice(-6)}},rgb_to_rgb_str:{enumerable:!0,writable:!1,configurable:!1,value:function(a,f,d,c){c=c===void 0?1:c;c=c<0?0:c>1?1:c;return c===1?"rgb("+a+","+f+","+d+")":"rgba("+a+","+f+","+d+","+c+")"}},get_element:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return typeof a==="string"?(a=a[0]==="#"?a.slice(1):a,document.getElementById(a)):a&&a.tagName?a:null}},get_style_property:{enumerable:!0,
writable:!1,configurable:!1,value:function(a,f,d){try{if(d===void 0&&document.defaultView&&document.defaultView.getComputedStyle)return document.defaultView.getComputedStyle(a,null)[f];else if(a.currentStyle)return a.currentStyle[f];else if(a.style)return a.style[f];else throw new ReferenceError("get_style_property: Cannot read property '"+f+"' of "+a+".");}catch(c){throw new ReferenceError("get_style_property: Cannot read property '"+f+"' of "+a+".");}}},get_element_property:{enumerable:!0,writable:!1,
configurable:!1,value:function(a,f,d,c){var d=d||!1,e;try{e=doodle.utils.get_style_property(a,f,c)}catch(b){e=void 0}if(e===void 0||e===null||e==="")e=a.getAttribute(f);if(d!==!1)switch(d){case "int":e=window.parseInt(e,10);e=window.isNaN(e)?null:e;break;case "number":case "float":e=window.parseFloat(e);e=window.isNaN(e)?null:e;break;case "string":e=String(e)}return e}},set_element_property:{enumerable:!0,writable:!1,configurable:!1,value:function(a,f,d,c){switch(c===void 0?"css":c){case "css":a.style[f]=
d;break;case "html":a.setAttribute(f,d);break;default:throw new SyntaxError("set_element_property: type must be 'css' property or 'html' attribute.");}return d}},create_scene_path:{enumerable:!0,writable:!1,configurable:!1,value:function f(d,c,e){var c=c===void 0?[]:c,b=d.children.length;(e===void 0?0:e)&&c.splice(0,c.length);if(b!==0)for(;b--;)f(d.children[b],c,!1);c.push(d);return c}}})})();
Object.defineProperty(doodle,"Keyboard",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{BACKSPACE:{enumerable:!0,writable:!1,configurable:!1,value:8},TAB:{enumerable:!0,writable:!1,configurable:!1,value:9},ENTER:{enumerable:!0,writable:!1,configurable:!1,value:13},COMMAND:{enumerable:!0,writable:!1,configurable:!1,value:15},SHIFT:{enumerable:!0,writable:!1,configurable:!1,value:16},CONTROL:{enumerable:!0,writable:!1,configurable:!1,value:17},ALTERNATE:{enumerable:!0,writable:!1,
configurable:!1,value:18},PAUSE:{enumerable:!0,writable:!1,configurable:!1,value:19},CAPS_LOCK:{enumerable:!0,writable:!1,configurable:!1,value:20},NUMPAD:{enumerable:!0,writable:!1,configurable:!1,value:21},ESCAPE:{enumerable:!0,writable:!1,configurable:!1,value:27},SPACE:{enumerable:!0,writable:!1,configurable:!1,value:32},PAGE_UP:{enumerable:!0,writable:!1,configurable:!1,value:33},PAGE_DOWN:{enumerable:!0,writable:!1,configurable:!1,value:34},END:{enumerable:!0,writable:!1,configurable:!1,value:35},
HOME:{enumerable:!0,writable:!1,configurable:!1,value:36},LEFT:{enumerable:!0,writable:!1,configurable:!1,value:37},UP:{enumerable:!0,writable:!1,configurable:!1,value:38},RIGHT:{enumerable:!0,writable:!1,configurable:!1,value:39},DOWN:{enumerable:!0,writable:!1,configurable:!1,value:40},INSERT:{enumerable:!0,writable:!1,configurable:!1,value:45},DELETE:{enumerable:!0,writable:!1,configurable:!1,value:46},NUMBER_0:{enumerable:!0,writable:!1,configurable:!1,value:48},NUMBER_1:{enumerable:!0,writable:!1,
configurable:!1,value:49},NUMBER_2:{enumerable:!0,writable:!1,configurable:!1,value:50},NUMBER_3:{enumerable:!0,writable:!1,configurable:!1,value:51},NUMBER_4:{enumerable:!0,writable:!1,configurable:!1,value:52},NUMBER_5:{enumerable:!0,writable:!1,configurable:!1,value:53},NUMBER_6:{enumerable:!0,writable:!1,configurable:!1,value:54},NUMBER_7:{enumerable:!0,writable:!1,configurable:!1,value:55},NUMBER_8:{enumerable:!0,writable:!1,configurable:!1,value:56},NUMBER_9:{enumerable:!0,writable:!1,configurable:!1,
value:57},A:{enumerable:!0,writable:!1,configurable:!1,value:65},B:{enumerable:!0,writable:!1,configurable:!1,value:66},C:{enumerable:!0,writable:!1,configurable:!1,value:67},D:{enumerable:!0,writable:!1,configurable:!1,value:68},E:{enumerable:!0,writable:!1,configurable:!1,value:69},F:{enumerable:!0,writable:!1,configurable:!1,value:70},G:{enumerable:!0,writable:!1,configurable:!1,value:71},H:{enumerable:!0,writable:!1,configurable:!1,value:72},I:{enumerable:!0,writable:!1,configurable:!1,value:73},
J:{enumerable:!0,writable:!1,configurable:!1,value:74},K:{enumerable:!0,writable:!1,configurable:!1,value:75},L:{enumerable:!0,writable:!1,configurable:!1,value:76},M:{enumerable:!0,writable:!1,configurable:!1,value:77},N:{enumerable:!0,writable:!1,configurable:!1,value:78},O:{enumerable:!0,writable:!1,configurable:!1,value:79},P:{enumerable:!0,writable:!1,configurable:!1,value:80},Q:{enumerable:!0,writable:!1,configurable:!1,value:81},R:{enumerable:!0,writable:!1,configurable:!1,value:82},S:{enumerable:!0,
writable:!1,configurable:!1,value:83},T:{enumerable:!0,writable:!1,configurable:!1,value:84},U:{enumerable:!0,writable:!1,configurable:!1,value:85},V:{enumerable:!0,writable:!1,configurable:!1,value:86},W:{enumerable:!0,writable:!1,configurable:!1,value:87},X:{enumerable:!0,writable:!1,configurable:!1,value:88},Y:{enumerable:!0,writable:!1,configurable:!1,value:89},Z:{enumerable:!0,writable:!1,configurable:!1,value:90},WINDOWS_KEY:{enumerable:!0,writable:!1,configurable:!1,value:91},NUMPAD_0:{enumerable:!0,
writable:!1,configurable:!1,value:96},NUMPAD_1:{enumerable:!0,writable:!1,configurable:!1,value:97},NUMPAD_2:{enumerable:!0,writable:!1,configurable:!1,value:98},NUMPAD_3:{enumerable:!0,writable:!1,configurable:!1,value:99},NUMPAD_4:{enumerable:!0,writable:!1,configurable:!1,value:100},NUMPAD_5:{enumerable:!0,writable:!1,configurable:!1,value:101},NUMPAD_6:{enumerable:!0,writable:!1,configurable:!1,value:102},NUMPAD_7:{enumerable:!0,writable:!1,configurable:!1,value:103},NUMPAD_8:{enumerable:!0,writable:!1,
configurable:!1,value:104},NUMPAD_9:{enumerable:!0,writable:!1,configurable:!1,value:105},NUMPAD_MULTIPLY:{enumerable:!0,writable:!1,configurable:!1,value:106},NUMPAD_ADD:{enumerable:!0,writable:!1,configurable:!1,value:107},NUMPAD_ENTER:{enumerable:!0,writable:!1,configurable:!1,value:108},NUMPAD_SUBTRACT:{enumerable:!0,writable:!1,configurable:!1,value:109},NUMPAD_DECIMAL:{enumerable:!0,writable:!1,configurable:!1,value:110},NUMPAD_DIVIDE:{enumerable:!0,writable:!1,configurable:!1,value:111},F1:{enumerable:!0,
writable:!1,configurable:!1,value:112},F2:{enumerable:!0,writable:!1,configurable:!1,value:113},F3:{enumerable:!0,writable:!1,configurable:!1,value:114},F4:{enumerable:!0,writable:!1,configurable:!1,value:115},F5:{enumerable:!0,writable:!1,configurable:!1,value:116},F6:{enumerable:!0,writable:!1,configurable:!1,value:117},F7:{enumerable:!0,writable:!1,configurable:!1,value:118},F8:{enumerable:!0,writable:!1,configurable:!1,value:119},F9:{enumerable:!0,writable:!1,configurable:!1,value:120},F10:{enumerable:!0,
writable:!1,configurable:!1,value:121},F11:{enumerable:!0,writable:!1,configurable:!1,value:122},F12:{enumerable:!0,writable:!1,configurable:!1,value:123},F13:{enumerable:!0,writable:!1,configurable:!1,value:124},F14:{enumerable:!0,writable:!1,configurable:!1,value:125},F15:{enumerable:!0,writable:!1,configurable:!1,value:126},SCROLL:{enumerable:!0,writable:!1,configurable:!1,value:145},SEMICOLON:{enumerable:!0,writable:!1,configurable:!1,value:186},EQUAL:{enumerable:!0,writable:!1,configurable:!1,
value:187},COMMA:{enumerable:!0,writable:!1,configurable:!1,value:188},MINUS:{enumerable:!0,writable:!1,configurable:!1,value:189},PERIOD:{enumerable:!0,writable:!1,configurable:!1,value:190},SLASH:{enumerable:!0,writable:!1,configurable:!1,value:191},BACKQUOTE:{enumerable:!0,writable:!1,configurable:!1,value:192},LEFTBRACKET:{enumerable:!0,writable:!1,configurable:!1,value:219},BACKSLASH:{enumerable:!0,writable:!1,configurable:!1,value:220},RIGHTBRACKET:{enumerable:!0,writable:!1,configurable:!1,
value:221},QUOTE:{enumerable:!0,writable:!1,configurable:!1,value:222}})});Object.defineProperty(doodle,"GradientType",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{LINEAR:{enumerable:!0,writable:!1,configurable:!1,value:"linearGradient"},RADIAL:{enumerable:!0,writable:!1,configurable:!1,value:"radialGradient"}})});
Object.defineProperty(doodle,"Pattern",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{REPEAT:{enumerable:!0,writable:!1,configurable:!1,value:"repeat"},REPEAT_X:{enumerable:!0,writable:!1,configurable:!1,value:"repeat-x"},REPEAT_Y:{enumerable:!0,writable:!1,configurable:!1,value:"repeat-y"},NO_REPEAT:{enumerable:!0,writable:!1,configurable:!1,value:"no-repeat"}})});
Object.defineProperty(doodle,"LineCap",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{BUTT:{enumerable:!0,writable:!1,configurable:!1,value:"butt"},ROUND:{enumerable:!0,writable:!1,configurable:!1,value:"round"},SQUARE:{enumerable:!0,writable:!1,configurable:!1,value:"square"}})});
Object.defineProperty(doodle,"LineJoin",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{MITER:{enumerable:!0,writable:!1,configurable:!1,value:"miter"},ROUND:{enumerable:!0,writable:!1,configurable:!1,value:"round"},BEVEL:{enumerable:!0,writable:!1,configurable:!1,value:"bevel"}})});
(function(){var a,f,d;doodle.events.Event=doodle.events.createEvent=function(c,e,b){var g=Object.create(a),k=arguments.length,j,h;Object.defineProperties(g,f);Object.defineProperties(g,function(){var b,a,d,g=!1,e=0,c=null,k=null,s=null,r=new Date,t=!0,i=!1,q=!1;h=function(h,y,j){y=y===void 0?!1:y;j=j===void 0?!1:j;y!==!1?k=c=y:(c=h.currentTarget,k=h.target);b=j?j:h.type;a=h.bubbles;d=h.cancelable;g=h.cancelBubble;e=h.eventPhase;s=h.srcElement;r=h.timeStamp;t=h.returnValue;h.__cancel&&(i=!0);h.__cancelNow&&
(q=!0)};return{id:function(){var b=null;return{enumerable:!0,configurable:!1,get:function(){return b===null?this.toString()+"[type="+this.type+"]":b},set:function(a){b=a}}}(),type:{enumerable:!0,configurable:!1,get:function(){return b}},__setType:{enumerable:!1,value:function(a){b=a}},bubbles:{enumerable:!0,configurable:!1,get:function(){return a}},cancelable:{enumerable:!0,configurable:!1,get:function(){return d}},cancelBubble:{enumerable:!0,configurable:!1,get:function(){return g},set:function(b){g=
b}},__cancel:{enumerable:!1,configurable:!1,get:function(){return i}},__cancelNow:{enumerable:!1,configurable:!1,get:function(){return q}},currentTarget:{enumerable:!0,configurable:!1,get:function(){return c}},__setCurrentTarget:{enumerable:!1,value:function(b){c=b;return this}},target:{enumerable:!0,configurable:!1,get:function(){return k}},__setTarget:{enumerable:!1,value:function(b){k=b;return this}},eventPhase:{enumerable:!0,configurable:!1,get:function(){return e}},__setEventPhase:{enumerable:!1,
value:function(b){e=b;return this}},srcElement:{enumerable:!0,configurable:!1,get:function(){return s}},timeStamp:{enumerable:!0,configurable:!1,get:function(){return r}},returnValue:{enumerable:!0,configurable:!1,get:function(){return t}},initEvent:{enumerable:!0,configurable:!1,value:function(h,g,e){b=h===void 0?"undefined":h;a=g===void 0?!1:g;d=e===void 0?!1:e;return this}},preventDefault:{enumerable:!0,configurable:!1,value:function(){}},stopPropagation:{enumerable:!0,configurable:!1,value:function(){if(this.cancelable)i=
!0;else throw Error(this.id+" Event.stopPropagation: Event can not be cancelled.");}},stopImmediatePropagation:{enumerable:!0,configurable:!1,value:function(){if(this.cancelable)q=i=!0;else throw Error(this.id+" Event.stopImmediatePropagation: Event can not be cancelled.");}},__copyEventProperties:{enumerable:!1,configurable:!1,value:function(b,a,d){h(b,a===void 0?!1:a,d===void 0?!1:d);return this}}}}());if(k===1&&(typeof arguments[0]==="function"||d(arguments[0])))j=arguments[0],c=void 0;j?typeof j===
"function"?j.call(g):h(j,!1,!1):g.initEvent(c,e,b);return g};f={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object Event]"}}};a=Object.create({},{CAPTURING_PHASE:{enumerable:!0,writable:!1,configurable:!1,value:1},AT_TARGET:{enumerable:!0,writable:!1,configurable:!1,value:2},BUBBLING_PHASE:{enumerable:!0,writable:!1,configurable:!1,value:3},MOUSEDOWN:{enumerable:!0,writable:!1,configurable:!1,value:1},MOUSEUP:{enumerable:!0,writable:!1,configurable:!1,value:2},MOUSEOVER:{enumerable:!0,
writable:!1,configurable:!1,value:4},MOUSEOUT:{enumerable:!0,writable:!1,configurable:!1,value:8},MOUSEMOVE:{enumerable:!0,writable:!1,configurable:!1,value:16},MOUSEDRAG:{enumerable:!0,writable:!1,configurable:!1,value:32},CLICK:{enumerable:!0,writable:!1,configurable:!1,value:64},DBLCLICK:{enumerable:!0,writable:!1,configurable:!1,value:128},KEYDOWN:{enumerable:!0,writable:!1,configurable:!1,value:256},KEYUP:{enumerable:!0,writable:!1,configurable:!1,value:512},KEYPRESS:{enumerable:!0,writable:!1,
configurable:!1,value:1024},DRAGDROP:{enumerable:!0,writable:!1,configurable:!1,value:2048},FOCUS:{enumerable:!0,writable:!1,configurable:!1,value:4096},BLUR:{enumerable:!0,writable:!1,configurable:!1,value:8192},SELECT:{enumerable:!0,writable:!1,configurable:!1,value:16384},CHANGE:{enumerable:!0,writable:!1,configurable:!1,value:32768}});d=doodle.events.Event.isEvent=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object Event]"||a.constructor&&a.constructor.name==="Event")return!0;
else a=Object.getPrototypeOf(a);return!1}})();
(function(){var a,f=doodle.events.Event.isEvent;doodle.events.UIEvent=doodle.events.createUIEvent=function(d,c,e,b,g){var k,j,h;f(arguments[0])?(j=arguments[0],d=void 0,k=Object.create(doodle.events.createEvent(j))):typeof arguments[0]==="function"?(j=arguments[0],d=void 0,k=Object.create(doodle.events.createEvent(""))):(c=c===void 0?!1:c,e=e===void 0?!1:e,k=Object.create(doodle.events.createEvent(d,c,e)));Object.defineProperties(k,a);Object.defineProperties(k,function(){var b=null,a=0,d=0,g=0,e=
0,c=0,k=0,j=0,r=0;h=function(h){if(h.view!==void 0)b=h.view;if(h.detail!==void 0)a=h.detail;if(h.which!==void 0)d=h.which;if(h.charCode!==void 0)g=h.charCode;if(h.keyCode!==void 0)e=h.keyCode;if(h.layerX!==void 0)c=h.layerX;if(h.layerY!==void 0)k=h.layerY;if(h.pageX!==void 0)j=h.pageX;if(h.pageY!==void 0)r=h.pageY};return{view:{enumerable:!0,configurable:!1,get:function(){return b}},detail:{enumerable:!0,configurable:!1,get:function(){return a}},which:{enumerable:!0,configurable:!1,get:function(){return d}},
charCode:{enumerable:!0,configurable:!1,get:function(){return g}},keyCode:{enumerable:!0,configurable:!1,get:function(){return e}},layerX:{enumerable:!0,configurable:!1,get:function(){return c}},layerY:{enumerable:!0,configurable:!1,get:function(){return k}},pageX:{enumerable:!0,configurable:!1,get:function(){return j}},pageY:{enumerable:!0,configurable:!1,get:function(){return r}},initUIEvent:{value:function(d,h,g,e,c){b=e===void 0?null:e;a=c===void 0?0:c;this.initEvent(d,h===void 0?!1:h,g===void 0?
!1:g);return this}},__copyUIEventProperties:{enumerable:!1,configurable:!1,value:function(b,a,d){a=a===void 0?!1:a;d=d===void 0?!1:d;h(b);return this.__copyEventProperties(b,a,d)}}}}());j?typeof j==="function"?j.call(k):h(j):k.initUIEvent(d,c,e,b,g);return k};a={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object UIEvent]"}}}})();
doodle.events.UIEvent.isUIEvent=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object UIEvent]"||a.constructor&&a.constructor.name==="UIEvent")return!0;else a=Object.getPrototypeOf(a);return!1};
(function(){var a,f=doodle.events.Event.isEvent;doodle.events.MouseEvent=doodle.events.createMouseEvent=function(d,c,e,b,g,k,j,h,l,n,m,o,u,p,v){var s,r,t;f(arguments[0])?(r=arguments[0],d=void 0,s=Object.create(doodle.events.createUIEvent(r))):typeof arguments[0]==="function"?(r=arguments[0],d=void 0,s=Object.create(doodle.events.createUIEvent(""))):(c=c===void 0?!1:c,e=e===void 0?!1:e,b=b===void 0?null:b,g=g===void 0?0:g,s=Object.create(doodle.events.createUIEvent(d,c,e,b,g)));Object.defineProperties(s,
a);Object.defineProperties(s,function(){var b=0,a=0,d=0,h=0,g=0,e=0,c=0,l=0,k=!1,n=!1,r=!1,u=!1,m=0,j=null;t=function(p){b=p.x!==void 0?p.x:0;a=p.y!==void 0?p.y:0;d=p.offsetX!==void 0?p.offsetX:0;h=p.offsetY!==void 0?p.offsetY:0;if(p.screenX!==void 0)g=p.screenX;if(p.screenY!==void 0)e=p.screenY;if(p.clientX!==void 0)c=p.clientX;if(p.clientY!==void 0)l=p.clientY;if(p.ctrlKey!==void 0)k=p.ctrlKey;if(p.altKey!==void 0)n=p.altKey;if(p.shiftKey!==void 0)r=p.shiftKey;if(p.metaKey!==void 0)u=p.metaKey;
if(p.button!==void 0)m=p.button;if(p.relatedTarget!==void 0)j=p.relatedTarget};return{x:{enumerable:!0,configurable:!1,get:function(){return b}},y:{enumerable:!0,configurable:!1,get:function(){return a}},screenX:{enumerable:!0,configurable:!1,get:function(){return g}},screenY:{enumerable:!0,configurable:!1,get:function(){return e}},clientX:{enumerable:!0,configurable:!1,get:function(){return c}},clientY:{enumerable:!0,configurable:!1,get:function(){return l}},offsetX:{enumerable:!0,configurable:!1,
get:function(){return d}},offsetY:{enumerable:!0,configurable:!1,get:function(){return h}},ctrlKey:{enumerable:!0,configurable:!1,get:function(){return k}},altKey:{enumerable:!0,configurable:!1,get:function(){return n}},shiftKey:{enumerable:!0,configurable:!1,get:function(){return r}},metaKey:{enumerable:!0,configurable:!1,get:function(){return u}},button:{enumerable:!0,configurable:!1,get:function(){return m}},relatedTarget:{enumerable:!0,configurable:!1,get:function(){return j}},initMouseEvent:{value:function(b,
a,d,h,q,p,i,s,t,f,y,x,o,I,E){v=E===void 0?null:E;g=p===void 0?0:p;e=i===void 0?0:i;c=s===void 0?0:s;l=t===void 0?0:t;k=f===void 0?!1:f;n=y===void 0?!1:y;r=x===void 0?!1:x;u=o===void 0?!1:o;m=I===void 0?0:I;j=E;return this.initUIEvent(b,a===void 0?!1:a,d===void 0?!1:d,h===void 0?null:h,q===void 0?0:q)}},getModifierState:{value:function(b){switch(b){case "Alt":return n;case "Control":return k;case "Meta":return u;case "Shift":return r;default:return!1}}},__copyMouseEventProperties:{enumerable:!1,configurable:!1,
value:function(b,a,d){a=a===void 0?!1:a;d=d===void 0?!1:d;t(b);return this.__copyUIEventProperties(b,a,d)}}}}());r?typeof r==="function"?r.call(s):t(r):s.initMouseEvent(d,c,e,b,g,k,j,h,l,n,m,o,u,p,v);return s};a={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object MouseEvent]"}}}})();
doodle.events.MouseEvent.isMouseEvent=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object MouseEvent]"||a.constructor&&(a.constructor.name==="MouseEvent"||a.constructor.name==="WheelEvent"))return!0;else a=Object.getPrototypeOf(a);return!1};
(function(){var a,f=doodle.events.Event.isEvent;doodle.events.TouchEvent=doodle.events.createTouchEvent=function(d,c,e,b,g,k,j,h,l,n,m,o,u,p,v,s,r,t){var i,q,x;f(arguments[0])?(q=arguments[0],d=void 0,i=Object.create(doodle.events.createUIEvent(q))):typeof arguments[0]==="function"?(q=arguments[0],d=void 0,i=Object.create(doodle.events.createUIEvent(""))):(c=c===void 0?!1:c,e=e===void 0?!1:e,b=b===void 0?null:b,g=g===void 0?0:g,i=Object.create(doodle.events.createUIEvent(d,c,e,b,g)));Object.defineProperties(i,
a);Object.defineProperties(i,function(){var b=0,a=0,d=0,h=0,g=!1,e=!1,c=!1,q=!1,l=null,k=null,n=null,p=1,r=0;x=function(i){if(i.screenX!==void 0)b=i.screenX;if(i.screenY!==void 0)a=i.screenY;if(i.clientX!==void 0)d=i.clientX;if(i.clientY!==void 0)h=i.clientY;if(i.ctrlKey!==void 0)g=i.ctrlKey;if(i.altKey!==void 0)e=i.altKey;if(i.shiftKey!==void 0)c=i.shiftKey;if(i.metaKey!==void 0)q=i.metaKey;if(i.touches!==void 0)l=i.touches;if(i.targetTouches!==void 0)k=i.targetTouches;if(i.changedTouches!==void 0)n=
i.changedTouches;if(i.scale!==void 0)p=i.scale;if(i.rotation!==void 0)r=i.rotation};return{screenX:{enumerable:!0,configurable:!1,get:function(){return b}},screenY:{enumerable:!0,configurable:!1,get:function(){return a}},clientX:{enumerable:!0,configurable:!1,get:function(){return d}},clientY:{enumerable:!0,configurable:!1,get:function(){return h}},ctrlKey:{enumerable:!0,configurable:!1,get:function(){return g}},altKey:{enumerable:!0,configurable:!1,get:function(){return e}},shiftKey:{enumerable:!0,
configurable:!1,get:function(){return c}},metaKey:{enumerable:!0,configurable:!1,get:function(){return q}},touches:{enumerable:!0,configurable:!1,get:function(){return l}},targetTouches:{enumerable:!0,configurable:!1,get:function(){return k}},changedTouches:{enumerable:!0,configurable:!1,get:function(){return n}},scale:{enumerable:!0,configurable:!1,get:function(){return p}},rotation:{enumerable:!0,configurable:!1,get:function(){return r}},initTouchEvent:{value:function(i,u,m,j,s,t,f,x,v,o,M,I,E,
N,O,P,Q,R){b=t===void 0?0:t;a=f===void 0?0:f;d=x===void 0?0:x;h=v===void 0?0:v;g=o===void 0?!1:o;e=M===void 0?!1:M;c=I===void 0?!1:I;q=E===void 0?!1:E;l=N===void 0?null:N;k=O===void 0?null:O;n=P===void 0?null:P;p=Q===void 0?1:Q;r=R===void 0?0:R;this.initUIEvent(i,u===void 0?!1:u,m===void 0?!1:m,j===void 0?null:j,s===void 0?0:s);return this}},getModifierState:{value:function(b){switch(b){case "Alt":return e;case "Control":return g;case "Meta":return q;case "Shift":return c;default:return!1}}},__copyTouchEventProperties:{enumerable:!1,
configurable:!1,value:function(b,a,d){a=a===void 0?!1:a;d=d===void 0?!1:d;x(b);return this.__copyUIEventProperties(b,a,d)}}}}());q?typeof q==="function"?q.call(i):x(q):i.initTouchEvent(d,c,e,b,g,k,j,h,l,n,m,o,u,p,v,s,r,t);return i};a={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object TouchEvent]"}}}})();
doodle.events.TouchEvent.isTouchEvent=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object TouchEvent]"||a.constructor&&a.constructor.name==="TouchEvent")return!0;else a=Object.getPrototypeOf(a);return!1};
(function(){var a,f=doodle.events.Event.isEvent;doodle.events.TextEvent=doodle.events.createTextEvent=function(d,c,e,b,g,k){var j,h,l;f(arguments[0])?(h=arguments[0],d=void 0,j=Object.create(doodle.events.createUIEvent(h))):typeof arguments[0]==="function"?(h=arguments[0],d=void 0,j=Object.create(doodle.events.createUIEvent(""))):(c=c===void 0?!1:c,e=e===void 0?!1:e,b=b===void 0?null:b,j=Object.create(doodle.events.createUIEvent(d,c,e,b)));Object.defineProperties(j,a);Object.defineProperties(j,function(){var b=
"",a=doodle.events.TextEvent.INPUT_METHOD_UNKNOWN;l=function(d){if(d.data!==void 0)b=d.data;if(d.inputMode!==void 0)a=d.inputMode};return{data:{enumerable:!0,configurable:!1,get:function(){return b}},inputMode:{enumerable:!0,configurable:!1,get:function(){return a}},initTextEvent:{value:function(d,h,g,e,c,l){l=l===void 0?doodle.events.TextEvent.INPUT_METHOD_UNKNOWN:l;b=c===void 0?"":c;a=l;this.initUIEvent(d,h===void 0?!1:h,g===void 0?!1:g,e===void 0?null:e);return this}},__copyTextEventProperties:{enumerable:!1,
configurable:!1,value:function(b,a,d){a=a===void 0?!1:a;d=d===void 0?!1:d;l(b);return this.__copyUIEventProperties(b,a,d)}}}}());h?typeof h==="function"?h.call(j):l(h):j.initTextEvent(d,c,e,b,g,k);return j};a={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object TextEvent]"}}}})();
doodle.events.TextEvent.isTextEvent=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object TextEvent]"||a.constructor&&a.constructor.name==="TextEvent")return!0;else a=Object.getPrototypeOf(a);return!1};
(function(){var a,f=doodle.events.Event.isEvent;doodle.events.KeyboardEvent=doodle.events.createKeyboardEvent=function(d,c,e,b,g,k,j,h){var l,n,m;f(arguments[0])?(n=arguments[0],d=void 0,l=Object.create(doodle.events.createUIEvent(n))):typeof arguments[0]==="function"?(n=arguments[0],d=void 0,l=Object.create(doodle.events.createUIEvent(""))):(c=c===void 0?!1:c,e=e===void 0?!1:e,b=b===void 0?null:b,l=Object.create(doodle.events.createUIEvent(d,c,e,b)));Object.defineProperties(l,a);Object.defineProperties(l,
function(){var b="",a=0,d=!1,h=!1,g=!1,e=!1,c=!1;m=function(i){if(i.keyIdentifier!==void 0)b=i.keyIdentifier;if(i.keyLocation!==void 0)a=i.keyLocation;if(i.repeat!==void 0)d=i.repeat;if(i.ctrlKey!==void 0)h=i.ctrlKey;if(i.altKey!==void 0)g=i.altKey;if(i.shiftKey!==void 0)e=i.shiftKey;if(i.metaKey!==void 0)c=i.metaKey;if(i.altGraphKey!==void 0)g=i.altGraphKey};return{keyIdentifier:{enumerable:!0,configurable:!1,get:function(){return b}},keyLocation:{enumerable:!0,configurable:!1,get:function(){return a}},
repeat:{enumerable:!0,configurable:!1,get:function(){return d}},ctrlKey:{enumerable:!0,configurable:!1,get:function(){return h}},altKey:{enumerable:!0,configurable:!1,get:function(){return g}},shiftKey:{enumerable:!0,configurable:!1,get:function(){return e}},metaKey:{enumerable:!0,configurable:!1,get:function(){return c}},altGraphKey:{enumerable:!0,configurable:!1,get:function(){return!1}},initKeyboardEvent:{value:function(i,q,l,k,n,m,j,f){q=q===void 0?!1:q;l=l===void 0?!1:l;k=k===void 0?null:k;b=
n===void 0?"":n;a=m===void 0?0:m;d=f===void 0?!1:f;(j===void 0?"":j).split(" ").forEach(function(b){switch(b){case "Alt":g=!0;break;case "Control":h=!0;break;case "Meta":c=!0;break;case "Shift":e=!0}});this.initUIEvent(i,q,l,k);return this}},getModifierState:{value:function(b){switch(b){case "Alt":return g;case "Control":return h;case "Meta":return c;case "Shift":return e;default:return!1}}},__copyKeyboardEventProperties:{enumerable:!1,configurable:!1,value:function(b,a,d){a=a===void 0?!1:a;d=d===
void 0?!1:d;m(b);return this.__copyUIEventProperties(b,a,d)}}}}());n?typeof n==="function"?n.call(l):m(n):l.initKeyboardEvent(d,c,e,b,g,k,j,h);return l};a={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object KeyboardEvent]"}}}})();doodle.events.KeyboardEvent.isKeyboardEvent=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object KeyboardEvent]"||a.constructor&&a.constructor.name==="KeyboardEvent")return!0;else a=Object.getPrototypeOf(a);return!1};
Object.defineProperties(doodle.events.Event,{CAPTURING_PHASE:{enumerable:!0,writable:!1,configurable:!1,value:1},AT_TARGET:{enumerable:!0,writable:!1,configurable:!1,value:2},BUBBLING_PHASE:{enumerable:!0,writable:!1,configurable:!1,value:3},ADDED:{enumerable:!0,writable:!1,configurable:!1,value:"added"},REMOVED:{enumerable:!0,writable:!1,configurable:!1,value:"removed"},ANIMATION_FRAME:{enumerable:!0,writable:!1,configurable:!1,value:"animationFrame"},ENTER_FRAME:{enumerable:!0,writable:!1,configurable:!1,
value:"animationFrame"},LOAD:{enumerable:!0,writable:!1,configurable:!1,value:"load"},CHANGE:{enumerable:!0,writable:!1,configurable:!1,value:"change"}});Object.defineProperties(doodle.events.UIEvent,{FOCUS_IN:{enumerable:!0,writable:!1,configurable:!1,value:"focusIn"}});
Object.defineProperties(doodle.events.MouseEvent,{CLICK:{enumerable:!0,writable:!1,configurable:!1,value:"click"},DOUBLE_CLICK:{enumerable:!0,writable:!1,configurable:!1,value:"dblclick"},CONTEXT_MENU:{enumerable:!0,writable:!1,configurable:!1,value:"contextmenu"},MOUSE_DOWN:{enumerable:!0,writable:!1,configurable:!1,value:"mousedown"},MOUSE_UP:{enumerable:!0,writable:!1,configurable:!1,value:"mouseup"},MOUSE_WHEEL:{enumerable:!0,writable:!1,configurable:!1,value:"mousewheel"},MOUSE_MOVE:{enumerable:!0,
writable:!1,configurable:!1,value:"mousemove"},MOUSE_OUT:{enumerable:!0,writable:!1,configurable:!1,value:"mouseout"},MOUSE_OVER:{enumerable:!0,writable:!1,configurable:!1,value:"mouseover"},MOUSE_ENTER:{enumerable:!0,writable:!1,configurable:!1,value:"mouseenter"},MOUSE_LEAVE:{enumerable:!0,writable:!1,configurable:!1,value:"mouseleave"}});
Object.defineProperties(doodle.events.TouchEvent,{TOUCH_START:{enumerable:!0,writable:!1,configurable:!1,value:"touchstart"},TOUCH_MOVE:{enumerable:!0,writable:!1,configurable:!1,value:"touchmove"},TOUCH_END:{enumerable:!0,writable:!1,configurable:!1,value:"touchend"},TOUCH_CANCEL:{enumerable:!0,writable:!1,configurable:!1,value:"touchcancel"}});
Object.defineProperties(doodle.events.KeyboardEvent,{KEY_PRESS:{enumerable:!0,writable:!1,configurable:!1,value:"keypress"},KEY_UP:{enumerable:!0,writable:!1,configurable:!1,value:"keyup"},KEY_DOWN:{enumerable:!0,writable:!1,configurable:!1,value:"keydown"},KEY_LOCATION_STANDARD:{enumerable:!0,writable:!1,configurable:!1,value:0},KEY_LOCATION_LEFT:{enumerable:!0,writable:!1,configurable:!1,value:1},KEY_LOCATION_RIGHT:{enumerable:!0,writable:!1,configurable:!1,value:2},KEY_LOCATION_NUMPAD:{enumerable:!0,
writable:!1,configurable:!1,value:3},KEY_LOCATION_MOBILE:{enumerable:!0,writable:!1,configurable:!1,value:4},KEY_LOCATION_JOYSTICK:{enumerable:!0,writable:!1,configurable:!1,value:5}});
Object.defineProperties(doodle.events.TextEvent,{TEXT_INPUT:{enumerable:!0,writable:!1,configurable:!1,value:"textInput"},INPUT_METHOD_UNKNOWN:{enumerable:!0,writable:!1,configurable:!1,value:0},INPUT_METHOD_KEYBOARD:{enumerable:!0,writable:!1,configurable:!1,value:1},INPUT_METHOD_PASTE:{enumerable:!0,writable:!1,configurable:!1,value:2},INPUT_METHOD_DROP:{enumerable:!0,writable:!1,configurable:!1,value:3},INPUT_METHOD_IME:{enumerable:!0,writable:!1,configurable:!1,value:4},INPUT_METHOD_OPTION:{enumerable:!0,
writable:!1,configurable:!1,value:5},INPUT_METHOD_HANDWRITING:{enumerable:!0,writable:!1,configurable:!1,value:6},INPUT_METHOD_VOICE:{enumerable:!0,writable:!1,configurable:!1,value:7},INPUT_METHOD_MULTIMODAL:{enumerable:!0,writable:!1,configurable:!1,value:8},INPUT_METHOD_SCRIPT:{enumerable:!0,writable:!1,configurable:!1,value:9}});
(function(){var a={},f=Array(8);doodle.filters.ColorFilter=doodle.filters.createColorFilter=function(d,c,e,b,g,k,j,h){var l={},n=arguments.length;Object.defineProperties(l,a);Object.defineProperties(l,function(){var b=null,a=1,d=1,h=1,g=1,e=0,c=0,l=0,i=0;return{redMultiplier:{enumerable:!0,configurable:!1,get:function(){return a},set:function(b){a=b}},greenMultiplier:{enumerable:!0,configurable:!1,get:function(){return d},set:function(b){d=b}},blueMultiplier:{enumerable:!0,configurable:!1,get:function(){return h},
set:function(b){h=b}},alphaMultiplier:{enumerable:!0,configurable:!1,get:function(){return g},set:function(b){g=b}},redOffset:{enumerable:!0,configurable:!1,get:function(){return e},set:function(b){e=b}},greenOffset:{enumerable:!0,configurable:!1,get:function(){return c},set:function(b){c=b}},blueOffset:{enumerable:!0,configurable:!1,get:function(){return l},set:function(b){l=b}},alphaOffset:{enumerable:!0,configurable:!1,get:function(){return i},set:function(b){i=b}},id:{enumerable:!0,configurable:!1,
get:function(){return b===null?this.toString():b},set:function(a){b=a}},__applyFilter:{enumerable:!0,configurable:!1,value:function(b,k,n,j,m){var f=b.getImageData(k,n,j,m),z=f.data;j*=m;for(var A=a,C=e,F=d,J=c,B=h,G=l,H=g,K=i;--j;)m=j<<2,z[m]=z[m]*A+C,z[m+1]=z[m+1]*F+J,z[m+2]=z[m+2]*B+G,z[m+3]=z[m+3]*H+K;f.data=z;b.putImageData(f,k,n)}},__toArray:{enumerable:!1,writable:!1,configurable:!1,value:function(){f[0]=a;f[1]=d;f[2]=h;f[3]=g;f[4]=e;f[5]=c;f[6]=l;f[7]=i;return f}}}}());switch(n){case 8:l.compose(d,
c,e,b,g,k,j,h);break;case 1:n=arguments[0],d=void 0,typeof n==="function"?n.call(l):Array.isArray(n)?l.compose.apply(l,n):l.compose.apply(l,n.__toArray())}return l};a={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object ColorFilter]"}},toArray:{enumerable:!0,writable:!1,configurable:!1,value:function(){return this.__toArray().concat()}},compose:{enumerable:!0,writable:!1,configurable:!1,value:function(a,c,e,b,g,k,j,h){this.redMultiplier=a;this.greenMultiplier=c;this.blueMultiplier=
e;this.alphaMultiplier=b;this.redOffset=g;this.greenOffset=k;this.blueOffset=j;this.alphaOffset=h;return this}},clone:{enumerable:!0,writable:!1,configurable:!1,value:function(){return doodle.filters.createColorFilter(this.__toArray())}},equals:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return this.redMultiplier===a.redMultiplier&&this.greenMultiplier===a.greenMultiplier&&this.blueMultiplier===a.blueMultiplier&&this.alphaMultiplier===a.alphaMultiplier&&this.redOffset===a.redOffset&&
this.greenOffset===a.greenOffset&&this.blueOffset===a.blueOffset&&this.alphaOffset===a.alphaOffset}}}})();
(function(){var a,f,d=Array(2),c={x:0,y:0};doodle.geom.Point=doodle.geom.createPoint=function(e,b){var g={},c=arguments.length;Object.defineProperties(g,a);Object.defineProperties(g,function(){var b=0,a=0;return{x:{enumerable:!0,configurable:!1,get:function(){return b},set:function(a){b=a}},y:{enumerable:!0,configurable:!1,get:function(){return a},set:function(b){a=b}},__toArray:{enumerable:!1,writable:!1,configurable:!1,value:function(){d[0]=b;d[1]=a;return d}},id:function(){var b=null;return{enumerable:!0,
configurable:!1,get:function(){return b===null?this.toString():b},set:function(a){b=a}}}()}}());switch(c){case 2:g.compose(e,b);break;case 1:c=arguments[0],e=void 0,typeof c==="function"?c.call(g):Array.isArray(c)?g.compose.apply(g,c):g.compose(c.x,c.y)}return g};a={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"(x="+this.x+",y="+this.y+")"}},toArray:{enumerable:!0,writable:!1,configurable:!1,value:function(){return this.__toArray().concat()}},length:{enumerable:!0,configurable:!1,
get:function(){return f(c,this)}},compose:{enumerable:!0,writable:!1,configurable:!1,value:function(a,b){this.x=a;this.y=b;return this}},clone:{enumerable:!0,writable:!1,configurable:!1,value:function(){return doodle.geom.createPoint(this.x,this.y)}},equals:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return this.x===a.x&&this.y===a.y}},add:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return doodle.geom.createPoint(this.x+a.x,this.y+a.y)}},subtract:{enumerable:!0,writable:!1,
configurable:!1,value:function(a){return doodle.geom.createPoint(this.x-a.x,this.y-a.y)}},offset:{enumerable:!0,writable:!1,configurable:!1,value:function(a,b){this.x+=a;this.y+=b;return this}},normalize:{enumerable:!0,writable:!1,configurable:!1,value:function(a){this.x=this.x/this.length*a;this.y=this.y/this.length*a;return this}},interpolate:{enumerable:!0,writable:!1,configurable:!1,value:function(a,b,d){return doodle.geom.createPoint(a.x+(b.x-a.x)*d,a.y+(b.y-a.y)*d)}},polar:{enumerable:!0,writable:!1,
configurable:!1,value:function(a,b){return doodle.geom.createPoint(a*Math.cos(b),a*Math.sin(b))}}};f=doodle.geom.Point.distance=function(a,b){var d=b.x-a.x,c=b.y-a.y;return Math.sqrt(d*d+c*c)}})();doodle.geom.Point.isPoint=function(a){return typeof a==="object"&&typeof a.x==="number"&&typeof a.y==="number"};
(function(){var a,f=Array(6),d={x:null,y:null},c={a:null,b:null,c:null,d:null,tx:null,ty:null},e=doodle.geom.createPoint;doodle.geom.Matrix=doodle.geom.createMatrix=function(b,d,c,e,h,l){var n={},m=arguments.length;Object.defineProperties(n,a);Object.defineProperties(n,function(){var b=1,a=0,d=0,h=1,c=0,g=0;return{a:{enumerable:!0,configurable:!1,get:function(){return b},set:function(a){b=a}},b:{enumerable:!0,configurable:!1,get:function(){return a},set:function(b){a=b}},c:{enumerable:!0,configurable:!1,
get:function(){return d},set:function(b){d=b}},d:{enumerable:!0,configurable:!1,get:function(){return h},set:function(b){h=b}},tx:{enumerable:!0,configurable:!1,get:function(){return c},set:function(b){c=b}},ty:{enumerable:!0,configurable:!1,get:function(){return g},set:function(b){g=b}},__toArray:{enumerable:!1,writable:!1,configurable:!1,value:function(){f[0]=b;f[1]=a;f[2]=d;f[3]=h;f[4]=c;f[5]=g;return f}},id:function(){var b=null;return{enumerable:!0,configurable:!1,get:function(){return b===null?
this.toString():b},set:function(a){b=a}}}()}}());switch(m){case 6:n.compose(b,d,c,e,h,l);break;case 1:m=arguments[0],b=void 0,typeof m==="function"?m.call(n):Array.isArray(m)?n.compose.apply(n,m):n.compose(m.a,m.b,m.c,m.d,m.tx,m.ty)}return n};a={compose:{enumerable:!0,writable:!1,configurable:!1,value:function(b,a,d,c,h,e){this.a=b;this.b=a;this.c=d;this.d=c;this.tx=h;this.ty=e;return this}},toArray:{enumerable:!0,writable:!1,configurable:!1,value:function(){return this.__toArray().concat()}},toString:{enumerable:!0,
writable:!1,configurable:!1,value:function(){return"(a="+this.a+",b="+this.b+",c="+this.c+",d="+this.d+",tx="+this.tx+",ty="+this.ty+")"}},equals:{enumerable:!0,writable:!1,configurable:!1,value:function(b){return this.a===b.a&&this.b===b.b&&this.c===b.c&&this.d===b.d&&this.tx===b.tx&&this.ty===b.ty}},identity:{enumerable:!0,writable:!1,configurable:!1,value:function(){this.a=1;this.c=this.b=0;this.d=1;this.ty=this.tx=0;return this}},clone:{enumerable:!0,writable:!1,configurable:!1,value:function(){return doodle.geom.createMatrix(this.a,
this.b,this.c,this.d,this.tx,this.ty)}},multiply:{enumerable:!0,writable:!1,configurable:!1,value:function(b){return this.compose(this.a*b.a+this.c*b.b,this.b*b.a+this.d*b.b,this.a*b.c+this.c*b.d,this.b*b.c+this.d*b.d,this.a*b.tx+this.c*b.ty+this.tx,this.b*b.tx+this.d*b.ty+this.ty)}},rotate:{enumerable:!0,writable:!1,configurable:!1,value:function(b){var a=Math.cos(b),b=Math.sin(b);c.a=a;c.b=b;c.c=-b;c.d=a;c.tx=0;c.ty=0;return this.multiply(c)}},deltaRotate:{enumerable:!0,writable:!1,configurable:!1,
value:function(b){var a=this.tx,d=this.ty;this.rotate(b);this.tx=a;this.ty=d;return this}},rotation:{enumerable:!0,configurable:!1,get:function(){return Math.atan2(this.b,this.a)},set:function(b){var a=Math.cos(b),b=Math.sin(b);this.compose(a,b,-b,a,this.tx,this.ty)}},scale:{enumerable:!0,writable:!1,configurable:!1,value:function(b,a){c.a=b;c.b=0;c.c=0;c.d=a;c.tx=0;c.ty=0;return this.multiply(c)}},deltaScale:{enumerable:!0,writable:!1,configurable:!1,value:function(b,a){var d=this.tx,c=this.ty;this.scale(b,
a);this.tx=d;this.ty=c;return this}},translate:{enumerable:!0,writable:!1,configurable:!1,value:function(b,a){this.tx+=b;this.ty+=a;return this}},skew:{enumerable:!0,writable:!1,configurable:!1,value:function(b,a){var d=Math.tan(b),e=Math.tan(a);c.a=1;c.b=e;c.c=d;c.d=1;c.tx=0;c.ty=0;return this.multiply(c)}},deltaSkew:{enumerable:!0,writable:!1,configurable:!1,value:function(b,a){var d=this.tx,c=this.ty;this.skew(b,a);this.tx=d;this.ty=c;return this}},add:{enumerable:!0,writable:!1,configurable:!1,
value:function(b){this.a+=b.a;this.b+=b.b;this.c+=b.c;this.d+=b.d;this.tx+=b.tx;this.ty+=b.ty;return this}},invert:{enumerable:!0,writable:!1,configurable:!1,value:function(){var b=this.a*this.d-this.b*this.c;return this.compose(this.d/b,-this.b/b,-this.c/b,this.a/b,(this.ty*this.c-this.d*this.tx)/b,-(this.ty*this.a-this.b*this.tx)/b)}},transformPoint:{enumerable:!0,writable:!1,configurable:!1,value:function(b){return e(this.a*b.x+this.c*b.y+this.tx,this.b*b.x+this.d*b.y+this.ty)}},__transformPoint:{enumerable:!1,
writable:!1,configurable:!1,value:function(b){var a=b.x,d=b.y;b.x=this.a*a+this.c*d+this.tx;b.y=this.b*a+this.d*d+this.ty;return b}},deltaTransformPoint:{enumerable:!0,writable:!1,configurable:!1,value:function(b){return e(this.a*b.x+this.c*b.y,this.b*b.x+this.d*b.y)}},__deltaTransformPoint:{enumerable:!1,writable:!1,configurable:!1,value:function(b){var a=b.x,d=b.y;b.x=this.a*a+this.c*d;b.y=this.b*a+this.d*d;return b}},rotateAroundExternalPoint:{enumerable:!0,writable:!1,configurable:!1,value:function(b,
a){var e=Math.cos(a),f=Math.sin(a);c.a=e;c.b=f;c.c=-f;c.d=e;c.tx=0;c.ty=0;this.translate(-b.x,-b.y);d.x=c.a*this.tx+c.c*this.ty+c.tx;d.y=c.b*this.tx+c.d*this.ty+c.ty;this.tx=d.x;this.ty=d.y;return this.multiply(c).translate(b.x,b.y)}},rotateAroundInternalPoint:{enumerable:!0,writable:!1,configurable:!1,value:function(b,a){d.x=this.a*b.x+this.c*b.y+this.tx;d.y=this.b*b.x+this.d*b.y+this.ty;return this.rotateAroundExternalPoint(d,a)}},matchInternalPointWithExternal:{enumerable:!0,writable:!1,configurable:!1,
value:function(b,a){d.x=this.a*b.x+this.c*b.y+this.tx;d.y=this.b*b.x+this.d*b.y+this.ty;return this.translate(a.x-d.x,a.y-d.y)}},interpolate:{enumerable:!0,writable:!1,configurable:!1,value:function(b,a){this.a+=(b.a-this.a)*a;this.b+=(b.b-this.b)*a;this.c+=(b.c-this.c)*a;this.d+=(b.d-this.d)*a;this.tx+=(b.tx-this.tx)*a;this.ty+=(b.ty-this.ty)*a;return this}}}})();
doodle.geom.Matrix.isMatrix=function(a){return typeof a==="object"&&typeof a.a==="number"&&typeof a.b==="number"&&typeof a.c==="number"&&typeof a.d==="number"&&typeof a.tx==="number"&&typeof a.ty==="number"};
(function(){var a,f=Array(4);doodle.geom.Rectangle=doodle.geom.createRectangle=function(d,c,e,b){var g={},k=arguments.length;Object.defineProperties(g,a);Object.defineProperties(g,function(){var b=0,a=0,d=0,c=0;return{x:{enumerable:!0,configurable:!1,get:function(){return b},set:function(a){b=a}},y:{enumerable:!0,configurable:!1,get:function(){return a},set:function(b){a=b}},width:{enumerable:!0,configurable:!1,get:function(){return d},set:function(b){d=b}},height:{enumerable:!0,configurable:!1,get:function(){return c},
set:function(b){c=b}},__toArray:{enumerable:!1,writable:!1,configurable:!1,value:function(){f[0]=b;f[1]=a;f[2]=d;f[3]=c;return f}},id:function(){var b=null;return{enumerable:!0,configurable:!1,get:function(){return b===null?this.toString():b},set:function(a){b=a}}}()}}());switch(k){case 4:g.compose(d,c,e,b);break;case 1:k=arguments[0],d=void 0,typeof k==="function"?k.call(g):Array.isArray(k)?g.compose.apply(g,k):g.compose(k.x,k.y,k.width,k.height)}return g};a={top:{enumerable:!0,configurable:!1,get:function(){return this.y},
set:function(a){this.y=a;this.height-=a}},right:{enumerable:!0,configurable:!1,get:function(){return this.x+this.width},set:function(a){this.width=a-this.x}},bottom:{enumerable:!0,configurable:!1,get:function(){return this.y+this.height},set:function(a){this.height=a-this.y}},left:{enumerable:!0,configurable:!1,get:function(){return this.x},set:function(a){this.x=a;this.width-=a}},toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"(x="+this.x+",y="+this.y+",w="+this.width+
",h="+this.height+")"}},toArray:{enumerable:!0,writable:!1,configurable:!1,value:function(){return this.__toArray().concat()}},compose:{enumerable:!0,writable:!1,configurable:!1,value:function(a,c,e,b){this.x=a;this.y=c;this.width=e;this.height=b;return this}},__compose:{enumerable:!1,writable:!1,configurable:!1,value:function(a){this.compose.apply(this,a.__toArray());return this}},clone:{enumerable:!0,writable:!1,configurable:!1,value:function(){return doodle.geom.createRectangle(this.x,this.y,this.width,
this.height)}},offset:{enumerable:!0,writable:!1,configurable:!1,value:function(a,c){this.x+=a;this.y+=c;return this}},inflate:{enumerable:!0,writable:!1,configurable:!1,value:function(a,c){this.x-=a;this.width+=2*a;this.y-=c;this.height+=2*c;return this}},equals:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return this.x===a.x&&this.y===a.y&&this.width===a.width&&this.height===a.height}},isEmpty:{enumerable:!0,writable:!1,configurable:!1,value:function(){return this.width>=0||this.height>=
0}},contains:{enumerable:!1,writable:!1,configurable:!1,value:function(a,c){return a>=this.left&&a<=this.right&&c>=this.top&&c<=this.bottom}},containsPoint:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return this.contains(a.x,a.y)}},containsRect:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var c=a.x+a.width,e=a.y+a.height;return this.contains(a.x,a.y)&&this.contains(c,a.y)&&this.contains(c,e)&&this.contains(a.x,e)}},intersects:{enumerable:!0,writable:!1,configurable:!1,
value:function(a){var c=a.x+a.width,e=a.y+a.height;return this.contains(a.x,a.y)||this.contains(c,a.y)||this.contains(c,e)||this.contains(a.x,e)}},intersection:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var c=doodle.geom.createRectangle(0,0,0,0);if(this.intersects(a))c.left=Math.max(this.left,a.x),c.top=Math.max(this.top,a.y),c.right=Math.min(this.right,a.x+a.width),c.bottom=Math.min(this.bottom,a.y+a.height);return c}},__intersection:{enumerable:!1,writable:!1,configurable:!1,value:function(a){if(this.intersects(a))this.left=
Math.max(this.left,a.x),this.top=Math.max(this.top,a.y),this.right=Math.min(this.right,a.x+a.width),this.bottom=Math.min(this.bottom,a.y+a.height);return this}},union:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var c=doodle.geom.createRectangle(0,0,0,0);c.left=Math.min(this.left,a.x);c.top=Math.min(this.top,a.y);c.right=Math.max(this.right,a.x+a.width);c.bottom=Math.max(this.bottom,a.y+a.height);return c}},__union:{enumerable:!1,writable:!1,configurable:!1,value:function(a){var c=
Math.min(this.top,a.y),e=Math.max(this.right,a.x+a.width),b=Math.max(this.bottom,a.y+a.height);this.left=Math.min(this.left,a.x);this.top=c;this.right=e;this.bottom=b;return this}}}})();doodle.geom.Rectangle.isRectangle=function(a){return typeof a==="object"&&typeof a.x==="number"&&typeof a.y==="number"&&typeof a.width==="number"&&typeof a.height==="number"};
(function(){var a,f,d=doodle.events.Event.AT_TARGET,c=doodle.events.Event.BUBBLING_PHASE;doodle.Emitter=doodle.createEmitter=function(c){var b={};Object.defineProperties(b,a);Object.defineProperties(b,function(){var a={};return{allListeners:{enumerable:!0,configurable:!1,get:function(){return a}},listeners:{enumerable:!0,configurable:!1,value:function(b){return a.hasOwnProperty(b)?a[b]:[]}}}}());b.on=b.addListener;typeof c==="function"&&c.call(b);return b};a={toString:{enumerable:!0,writable:!1,configurable:!1,
value:function(){return"[object Emitter]"}},addListener:{enumerable:!0,writable:!1,configurable:!1,value:function(a,b){var c=this.allListeners;c.hasOwnProperty(a)||(c[a]=[]);c[a].push(b);f.indexOf(this)===-1&&f.push(this)}},once:{enumerable:!0,writable:!1,configurable:!1,value:function(a,b){var c=function(d){b(d);this.removeListener(a,c)}.bind(this);this.addListener(a,c)}},removeListener:{enumerable:!0,writable:!1,configurable:!1,value:function(a,b){var c=this.allListeners,d=this.listeners(a),j=d.length;
j>0&&(j=d.indexOf(b),j!==-1&&d.splice(j,1),d.length===0&&delete c[a],Object.keys(c).length===0&&f.splice(f.indexOf(this),1))}},removeAllListeners:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var b=this.allListeners;delete b[a];Object.keys(b).length===0&&f.splice(f.indexOf(this),1)}},handleEvent:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var b=this.listeners(a.type),c=b.length,d,f=0;if(c>0)for(a.__setCurrentTarget(this);f<c;f++){d=b[f].call(this,a);if(d===!1||a.returnValue===
!1)a.__cancel||a.stopPropagation();if(a.__cancelNow)break}return c>0?!0:!1}},emit:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var b=this,g,f=a.type;if(a.__cancel)return!1;a.target||a.__setTarget(this);g=a.target;for(a.__setEventPhase(c);b;){if(b.allListeners.hasOwnProperty(f)&&(b===g?(a.__setEventPhase(d),b.handleEvent(a),a.__setEventPhase(c)):b.handleEvent(a),a.__cancel||!a.bubbles||a.cancelBubble))break;b=b.parent}return!0}},broadcast:{enumerable:!0,writable:!1,configurable:!1,
value:function(a){var b=a.type,c=f,d=c.length;if(a.__cancel)throw Error(this+".broadcast: Can not dispatch a cancelled event.");for(a.target||a.__setTarget(this);d--;)if(c[d].allListeners.hasOwnProperty(b)&&c[d].handleEvent(a),a.__cancel)break;return!0}},hasListener:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return this.allListeners.hasOwnProperty(a)}},willTrigger:{enumerable:!0,writable:!1,configurable:!1,value:function(a){if(this.allListeners.hasOwnProperty(a))return!0;for(var b=
this.children,c=b?b.length:0;c--;)if(b[c].willTrigger(a))return!0;return!1}}};f=doodle.Emitter.emitter_queue=[]})();doodle.Emitter.isEmitter=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object Emitter]")return!0;else a=Object.getPrototypeOf(a);return!1};
(function(){var a=0,f,d=doodle.events.Event(doodle.events.Event.ADDED,!0),c=doodle.events.Event(doodle.events.Event.REMOVED,!0),e=doodle.geom.createPoint,b=doodle.geom.createMatrix,g=doodle.geom.createRectangle,k=doodle.utils.create_scene_path,j=Math.PI;doodle.Node=doodle.createNode=function(c){var d=Object.create(doodle.createEmitter());Object.defineProperties(d,f);Object.defineProperties(d,{id:function(){var b=typeof c==="string"?c:"node"+String("000"+a).slice(-3);a+=1;return{enumerable:!0,configurable:!0,
get:function(){return b},set:function(a){b=a}}}(),root:function(){var a=null;return{enumerable:!0,configurable:!0,get:function(){return a},set:function(b){a=b}}}(),parent:function(){var a=null;return{enumerable:!0,configurable:!0,get:function(){return a},set:function(b){a=b}}}(),children:function(){var a=[];return{enumerable:!0,configurable:!1,get:function(){return a}}}(),transform:function(){var a=b(1,0,0,1,0,0);return{enumerable:!0,configurable:!1,get:function(){return a},set:function(b){a=b}}}(),
visible:function(){var a=!0;return{enumerable:!0,configurable:!0,get:function(){return a},set:function(b){a=b}}}(),alpha:function(){var a=1;return{enumerable:!0,configurable:!0,get:function(){return a},set:function(b){a=b>1?1:b<0?0:b}}}(),getBounds:{enumerable:!0,writable:!0,configurable:!1,value:function(a){return this.__getBounds(a).clone()}},__getBounds:{enumerable:!1,writable:!0,configurable:!1,value:function(){var a=g(0,0,0,0);return function(b){for(var c=null,d,h=this.children,l=h.length;l--;)d=
h[l].__getBounds(b),d!==null&&(c===null?c=a.__compose(d):c.__union(d));return c}}()}});typeof c==="function"&&(c.call(d),c=void 0);return d};f={x:{enumerable:!0,configurable:!1,get:function(){return this.transform.tx},set:function(a){this.transform.tx=a}},y:{enumerable:!0,configurable:!1,get:function(){return this.transform.ty},set:function(a){this.transform.ty=a}},rotate:{enumerable:!0,configurable:!1,value:function(a){this.transform.rotate(a*j/180)}},rotation:{enumerable:!0,configurable:!0,get:function(){return this.transform.rotation*
180/j},set:function(a){this.transform.rotation=a*j/180}},scaleX:{enumerable:!0,configurable:!1,get:function(){return this.transform.a},set:function(a){this.transform.a=a}},scaleY:{enumerable:!0,configurable:!1,get:function(){return this.transform.d},set:function(a){this.transform.d=a}},context:{enumerable:!0,configurable:!0,get:function(){for(var a=this.parent;a;){if(a.context)return a.context;a=a.parent}return null}},__allTransforms:{enumerable:!1,configurable:!1,get:function(){var a=b(1,0,0,1,0,
0);return function(){var b=this.parent;for(a.compose.apply(a,this.transform.__toArray());b;)a.multiply(b.transform),b=b.parent;return a}}()},toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object Node]"}},addChildAt:{enumerable:!0,writable:!1,configurable:!1,value:function(a,b){var c=this.children,e=this.root,g=a.parent;if(c.indexOf(a)!==-1)return!1;g!==null&&g!==this&&a.parent.removeChild(a);a.parent=this;c.splice(b,0,a);if(e&&a.root!==e){e.__sortAllChildren();c=k(a,
[]);for(g=c.length;g--;)a=c[g],a.root=e,a.emit(d.__setTarget(null))}return a}},addChild:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return this.addChildAt(a,this.children.length)}},appendTo:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return doodle.Display.isDisplay(a)?a.children[0].addChild(this):a.addChild(this)}},createNode:{enumerable:!0,writable:!1,configurable:!1,value:function(){return this.addChild(doodle.createNode.apply(void 0,arguments))}},createSprite:{enumerable:!0,
writable:!1,configurable:!1,value:function(){return this.addChild(doodle.createSprite.apply(void 0,arguments))}},removeChildAt:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var a=this.children.splice(a,1)[0],b=k(a),d=b.length,e=d;if(this.root){for(;d--;)b[d].emit(c.__setTarget(null));for(;e--;)b[e].root=null}a.parent=null;this.root&&this.root.__sortAllChildren();return a}},removeChild:{enumerable:!1,writable:!1,configurable:!1,value:function(a){return this.removeChildAt(this.children.indexOf(a))}},
removeChildById:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return this.removeChild(this.getChildById(a))}},removeAllChildren:{enumerable:!0,writable:!1,configurable:!1,value:function(){var a=this.children,b=this.root,d=k(this,[]),e=a.length,g,f;d.pop();g=f=d.length;if(b)for(;g--;)d[g].emit(c.__setTarget(null));for(;f--;)d[f].root=null;for(;e--;)a[e].parent=null;a.length=0;b&&b.__sortAllChildren()}},getChildById:{enumerable:!0,writable:!1,configurable:!1,value:function(a){for(var b=
this.children,c=b.length,d=0;d<c;d++)if(b[d].id===a)return b[d]}},setChildIndex:{enumerable:!0,writable:!1,configurable:!1,value:function(a,b){var c=this.children,d=c.indexOf(a);c.splice(d,1);c.splice(b,0,a);this.root&&this.root.__sortAllChildren()}},swapChildrenAt:{enumerable:!0,writable:!1,configurable:!1,value:function(a,b){var c=this.children,d;d=c.splice(a,1,void 0)[0];c.splice(a,1,c.splice(b,1,void 0)[0]);c[c.indexOf(void 0)]=d;this.root&&this.root.__sortAllChildren()}},swapChildren:{enumerable:!0,
writable:!1,configurable:!1,value:function(a,b){var c=this.children;this.swapChildrenAt(c.indexOf(a),c.indexOf(b))}},swapDepths:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var b=this.parent,c;c=b.children;b.swapChildrenAt(c.indexOf(this),c.indexOf(a))}},swapDepthAt:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var b=this.parent;b.swapChildrenAt(b.children.indexOf(this),a)}},contains:{enumerable:!0,writable:!1,configurable:!1,value:function(a){return k(this,[]).indexOf(a)!==
-1?!0:!1}},localToGlobal:{enumerable:!0,writable:!1,configurable:!1,value:function(a){for(var b=this.parent,a=this.transform.transformPoint(a);b;)b.transform.__transformPoint(a),b=b.parent;return a}},__localToGlobal:{enumerable:!1,writable:!1,configurable:!1,value:function(a){for(var b=this;b;)b.transform.__transformPoint(a),b=b.parent;return a}},globalToLocal:{enumerable:!0,writable:!1,configurable:!1,value:function(a){var b={x:0,y:0};this.__localToGlobal(b);return e(a.x-b.x,a.y-b.y)}},__globalToLocal:{enumerable:!1,
writable:!1,configurable:!1,value:function(a){var b={x:0,y:0};this.__localToGlobal(b);a.x-=b.x;a.y-=b.y;return a}}}})();doodle.Node.isNode=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object Node]")return!0;else a=Object.getPrototypeOf(a);return!1};
(function(){var a,f=doodle.geom.createRectangle;doodle.Sprite=doodle.createSprite=function(d){var c=Object.create(doodle.createNode(typeof d==="string"?d:void 0));Object.defineProperties(c,a);Object.defineProperties(c,function(){var a=[];return{graphics:{enumerable:!1,configurable:!1,value:Object.create(doodle.createGraphics.call(c,a))},width:function(){var a=0;return{enumerable:!0,configurable:!1,get:function(){return a},set:function(c){a=c}}}(),height:function(){var a=0;return{enumerable:!0,configurable:!1,
get:function(){return a},set:function(c){a=c}}}(),getBounds:{enumerable:!0,writable:!0,configurable:!1,value:function(a){return this.__getBounds(a).clone()}},__getBounds:{enumerable:!1,writable:!0,configurable:!1,value:function(){var a=f(0,0,0,0);return function(c){var d=this.children,e=d.length,h,f=this.width,n=this.height,m=this.graphics;h={x:m.__minX,y:m.__minY};var o={x:m.__minX+f,y:m.__minY},f={x:m.__minX+f,y:m.__minY+n},n={x:m.__minX,y:m.__minY+n},m=Math.min,u=Math.max;this.__localToGlobal(h);
this.__localToGlobal(o);this.__localToGlobal(f);this.__localToGlobal(n);c.__globalToLocal(h);c.__globalToLocal(o);c.__globalToLocal(f);c.__globalToLocal(n);a.left=m(h.x,o.x,f.x,n.x);a.right=u(h.x,o.x,f.x,n.x);a.top=m(h.y,o.y,f.y,n.y);for(a.bottom=u(h.y,o.y,f.y,n.y);e--;)h=d[e].__getBounds(c),h!==null&&a.__union(h);return a}}()},hitTestObject:{enumerable:!0,writable:!0,configurable:!1,value:function(a){return this.getBounds(this).intersects(a.getBounds(this))}},hitTestPoint:{enumerable:!0,writable:!0,
configurable:!1,value:function(a,c){return this.getBounds(this).containsPoint(this.globalToLocal({x:a,y:c}))}},__draw:{enumerable:!1,writable:!1,configurable:!1,value:function(b){for(var d=0,f=a.length;d<f;d++)a[d].call(c,b)}}}}());typeof d==="function"&&d.call(c);return c};a={rotation:function(){var a=180/Math.PI,c=Math.PI/180;return{enumerable:!0,configurable:!1,get:function(){return this.transform.rotation*a},set:function(a){this.transform.rotation=a*c}}}(),toString:{enumerable:!1,writable:!1,
configurable:!1,value:function(){return"[object Sprite]"}},compose:{enumerable:!1,writable:!1,configurable:!1,value:function(a,c,e,b){this.x=a;this.y=c;this.width=e;this.height=b;return this}}}})();doodle.Sprite.isSprite=function(a){if(typeof a==="object")for(;a;)if(a.toLocaleString()==="[object Sprite]")return!0;else a=Object.getPrototypeOf(a);return!1};
(function(){var a,f=doodle.events.createEvent,d=doodle.events.Event.LOAD,c=doodle.utils.hex_to_rgb_str,e=doodle.utils.get_element;doodle.Graphics=doodle.createGraphics=function(b){var g={},k=this,j=0,h=0,l=1,n=doodle.LineCap.BUTT,m=doodle.LineJoin.MITER,o=10;Object.defineProperties(g,a);Object.defineProperties(g,{__minX:{enumerable:!1,writable:!0,configurable:!1,value:0},__minY:{enumerable:!1,writable:!0,configurable:!1,value:0},__maxX:{enumerable:!1,writable:!0,configurable:!1,value:0},__maxY:{enumerable:!1,
writable:!0,configurable:!1,value:0},lineWidth:{enumerable:!0,configurable:!1,get:function(){return l}},lineCap:{enumerable:!0,configurable:!1,get:function(){return n}},lineJoin:{enumerable:!0,configurable:!1,get:function(){return m}},lineMiter:{enumerable:!0,configurable:!1,get:function(){return o}},draw:{enumerable:!1,writable:!1,configurable:!1,value:function(a){b.push(a)}},clear:{enumerable:!1,writable:!1,configurable:!1,value:function(){b.length=0;k.width=0;j=h=this.__minX=this.__minY=this.__maxX=
this.__maxY=k.height=0;return this}},rect:{enumerable:!1,writable:!1,configurable:!1,value:function(a,c,d,e){this.__minX=Math.min(0,a,this.__minX);this.__minY=Math.min(0,c,this.__minY);this.__maxX=Math.max(0,a,a+d,this.__maxX);this.__maxY=Math.max(0,c,c+e,this.__maxY);k.width=-this.__minX+this.__maxX;k.height=-this.__minY+this.__maxY;b.push(function(b){b.beginPath();b.rect(a,c,d,e);b.closePath();b.stroke()});return this}},circle:{enumerable:!1,writable:!1,configurable:!1,value:function(a,c,d){this.__minX=
Math.min(0,-d+a,this.__minX);this.__minY=Math.min(0,-d+c,this.__minY);this.__maxX=Math.max(0,a,a+d,this.__maxX);this.__maxY=Math.max(0,c,c+d,this.__maxY);k.width=-this.__minX+this.__maxX;k.height=-this.__minY+this.__maxY;b.push(function(b){b.beginPath();b.arc(a,c,d,0,6.283185307179586,!0);b.closePath();b.stroke()});return this}},ellipse:{enumerable:!1,writable:!1,configurable:!1,value:function(a,c,d,e){var f=d/2,g=(e===void 0?d:e)/2,i=0.5522847498*f,h=0.5522847498*g;this.__minX=Math.min(0,-f+a,this.__minX);
this.__minY=Math.min(0,-g+c,this.__minY);this.__maxX=Math.max(0,a,a+f,this.__maxX);this.__maxY=Math.max(0,c,c+g,this.__maxY);k.width=-this.__minX+this.__maxX;k.height=-this.__minY+this.__maxY;b.push(function(b){b.beginPath();b.moveTo(a+f,c);b.bezierCurveTo(a+f,c-h,a+i,c-g,a,c-g);b.bezierCurveTo(a-i,c-g,a-f,c-h,a-f,c);b.bezierCurveTo(a-f,c+h,a-i,c+g,a,c+g);b.bezierCurveTo(a+i,c+g,a+f,c+h,a+f,c);b.closePath();b.stroke()});return this}},roundRect:{enumerable:!1,writable:!1,configurable:!1,value:function(a,
c,d,e,f,g){var f=f===void 0?0:f,g=g===void 0?0:g,i=a+d,h=i-f,j=a+f,y=c+e,l=y-g,m=c+g;this.__minX=Math.min(0,a,this.__minX);this.__minY=Math.min(0,c,this.__minY);this.__maxX=Math.max(0,a,a+d,this.__maxX);this.__maxY=Math.max(0,c,c+e,this.__maxY);k.width=-this.__minX+this.__maxX;k.height=-this.__minY+this.__maxY;b.push(function(b){b.beginPath();b.moveTo(j,c);b.beginPath();b.lineTo(h,c);b.quadraticCurveTo(i,c,i,m);b.lineTo(i,l);b.quadraticCurveTo(i,y,h,y);b.lineTo(j,y);b.quadraticCurveTo(a,y,a,l);b.lineTo(a,
m);b.quadraticCurveTo(a,c,j,c);b.closePath();b.stroke()});return this}},moveTo:{enumerable:!1,writable:!1,configurable:!1,value:function(a,c){b.push(function(b){b.moveTo(a,c)});j=a;h=c;return this}},lineTo:{enumerable:!1,writable:!1,configurable:!1,value:function(a,c){this.__minX=Math.min(0,a,j,this.__minX);this.__minY=Math.min(0,c,h,this.__minY);this.__maxX=Math.max(0,a,j,this.__maxX);this.__maxY=Math.max(0,c,h,this.__maxY);k.width=this.__maxX-this.__minX;k.height=this.__maxY-this.__minY;b.push(function(b){b.lineTo(a,
c)});j=a;h=c;return this}},curveTo:{enumerable:!1,writable:!1,configurable:!1,value:function(a,c,d,f){var e=j,g=h,i,q=0,l=0;i=(e-a)/(e-2*a+d);0<=i&&i<=1&&(q=(1-i)*(1-i)*e+2*(1-i)*i*a+i*i*d);i=(g-c)/(g-2*c+f);0<=i&&i<=1&&(l=(1-i)*(1-i)*g+2*(1-i)*i*c+i*i*f);this.__minX=Math.min(0,e,q,d,this.__minX);this.__minY=Math.min(0,g,l,f,this.__minY);this.__maxX=Math.max(0,e,q,d,this.__maxX);this.__maxY=Math.max(0,g,l,f,this.__maxY);k.width=-this.__minX+this.__maxX;k.height=-this.__minY+this.__maxY;b.push(function(b){b.quadraticCurveTo(a,
c,d,f)});j=d;h=f;return this}},bezierCurveTo:{enumerable:!1,writable:!1,configurable:!1,value:function(a,c,d,f,e,g){var i=Math.pow,q=Math.max,l=Math.min,m=j,n=h,w,o,z=0,A=0,C=0,F=0;for(w=0.1;w<1;w+=0.1)o=i(1-w,3)*m+3*i(1-w,2)*w*a+3*i(1-w,1)*i(w,2)*d+i(w,3)*e,o>z&&(z=o),o<A&&(A=o),o=i(1-w,3)*n+3*i(1-w,2)*w*c+3*i(1-w,1)*i(w,2)*f+i(w,3)*g,o>C&&(C=o),o<F&&(F=o);this.__minX=l(0,m,A,e,this.__minX);this.__minY=l(0,n,F,g,this.__minY);this.__maxX=q(0,m,z,e,this.__maxX);this.__maxY=q(0,n,C,g,this.__maxY);k.width=
-this.__minX+this.__maxX;k.height=-this.__minY+this.__maxY;b.push(function(b){b.bezierCurveTo(a,c,d,f,e,g)});j=e;h=g;return this}},beginFill:{enumerable:!1,writable:!1,configurable:!1,value:function(a,d){d=d===void 0?1:d;b.push(function(b){b.fillStyle=c(a,d)});return this}},beginLinearGradientFill:{enumerable:!0,writable:!1,configurable:!1,value:function(a,c,d,e,f,g,i){b.push(function(b){for(var h=doodle.utils.hex_to_rgb_str,j=b.createLinearGradient(a,c,d,e),l=f.length,k=0;k<l;k++)j.addColorStop(f[k],
h(g[k],i[k]));b.fillStyle=j});return this}},beginRadialGradientFill:{enumerable:!0,writable:!1,configurable:!1,value:function(a,c,d,e,f,g,i,h,j){b.push(function(b){for(var k=doodle.utils.hex_to_rgb_str,l=b.createRadialGradient(a,c,d,e,f,g),m=i.length,n=0;n<m;n++)l.addColorStop(i[n],k(h[n],j[n]));b.fillStyle=l});return this}},beginPatternFill:{enumerable:!0,writable:!1,configurable:!1,value:function(a,c){var g=null,h;h=doodle.Pattern;c=c===void 0?h.REPEAT:c;typeof a==="string"&&(a[0]==="#"?a=e(a):
function(){var b=window.encodeURI(a);a=new window.Image;a.src=b}());a.complete?g=a:(a.onload=function(){g=a;k.emit(f(d))},h=function(){throw new URIError(k.id+"Graphics.beginPatternFill(*image*,repeat): Unable to load "+a.src);},a.onerror=h,a.onabort=h);b.push(function(a){a.fillStyle=g?a.createPattern(g,c):"rgba(0,0,0,0)"});return this}},lineStyle:{enumerable:!0,writable:!1,configurable:!1,value:function(a,d,e,f,g,h){d=d===void 0?"#000000":d;e=e===void 0?1:e;f=f===void 0?doodle.LineCap.BUTT:f;g=g===
void 0?doodle.LineJoin.MITER:g;l=a===void 0?1:a;m=g;n=f;o=h===void 0?10:h;if(typeof d==="string"||typeof d==="number")d=c(d,e);else throw new TypeError(k+" Graphics.lineStyle(thickness,*color*,alpha,caps,joints,miterLimit): Color must be a hex value.");b.push(function(a){a.lineWidth=l;a.strokeStyle=d;a.lineCap=n;a.lineJoin=m;a.miterLimit=o});return this}},beginPath:{enumerable:!1,writable:!1,configurable:!1,value:function(){b.push(function(a){a.beginPath();a.moveTo(j,h)});return this}},closePath:{enumerable:!1,
writable:!1,configurable:!1,value:function(){b.push(function(a){a.closePath();a.stroke()});h=j=0;return this}},endFill:{enumerable:!1,writable:!1,configurable:!1,value:function(){b.push(function(a){a.fill()});return this}},stroke:{enumerable:!1,writable:!1,configurable:!1,value:function(){b.push(function(a){a.stroke()});h=j=0;return this}}});return g};a={toString:{enumerable:!1,writable:!1,configurable:!1,value:function(){return"[object Graphics]"}}}})();
(function(){var a,f=/^url\((.*)\)/,d=doodle.geom.createRectangle,c=doodle.utils.rgb_str_to_hex,e=doodle.utils.hex_to_rgb_str,b=doodle.utils.get_element,g=doodle.utils.get_element_property,k=doodle.utils.set_element_property;doodle.ElementNode=doodle.createElementNode=function(j,h){var l=Object.create(doodle.createNode(typeof h==="string"?h:void 0));Object.defineProperties(l,a);Object.defineProperties(l,function(){var a=null,h=l.id,j=l.alpha,u=l.visible,p=0,v=0,s=null,r=null,t="repeat",i=!0;return{element:{enumerable:!0,
configurable:!0,get:function(){return a},set:function(d){var m;d===null?(a!==null&&(typeof this.__removeDomElement==="function"&&this.__removeDomElement(a),r=s=null,t="repeat",this.parent||(v=p=0)),a=null):(a=d=b(d),this.__addDomElement(a),(d=g(a,"id"))?h=d:this.id=h,t=g(a,"backgroundRepeat")||t,s=(d=g(a,"backgroundColor",!1,!1))?c(d):s,d=g(a,"backgroundImage"),m=(d=!d||d==="none"?null:r.match(f))?d[1]:r,r=m)}},id:{enumerable:!0,configurable:!0,get:function(){return h},set:function(a){h=k(this.element,
"id",a,"html")}},width:{enumerable:!0,configurable:!0,get:function(){return p},set:function(a){k(this.element,"width",a+"px");p=a}},height:{enumerable:!0,configurable:!0,get:function(){return v},set:function(a){k(this.element,"height",a+"px");v=a}},backgroundColor:{enumerable:!0,configurable:!0,get:function(){return s},set:function(a){typeof a==="number"&&(a=e(a));k(this.element,"backgroundColor",a);s=c(g(this.element,"backgroundColor"))}},backgroundImage:{enumerable:!0,configurable:!0,get:function(){return r},
set:function(a){if(a){if(typeof a==="string"){if(a[0]==="#")a=b(a).src}else if(a&&a.tagName==="IMG")a=a.src;f.test(a)||(a="url("+window.encodeURI(a)+")");r=k(this.element,"backgroundImage",a)}else r=k(this.element,"backgroundImage",null)}},backgroundRepeat:{enumerable:!0,configurable:!0,get:function(){return t},set:function(a){t=k(this.element,"backgroundRepeat",a)}},alpha:{enumerable:!0,configurable:!0,get:function(){return j},set:function(a){k(this.element,"opacity",a)}},visible:{enumerable:!0,
configurable:!0,get:function(){return u},set:function(a){a?k(this.element,"visibility","visible"):k(this.element,"visibility","hidden");u=a}},clearBitmap:{enumerable:!1,configurable:!0,get:function(){return i},set:function(a){i=a}},__addDomElement:{enumerable:!1,configurable:!0,value:function(a){var b=g(a,"width","int")||a.width,a=g(a,"height","int")||a.height;typeof b==="number"&&(p=b);typeof a==="number"&&(v=a)}},__getBounds:{enumerable:!0,configurable:!0,value:function(){var a=d(0,0,0,0);return function(b){var c=
this.children,d=c.length,e,f=this.width,g=this.height;e={x:0,y:0};var h={x:f,y:0},f={x:f,y:g},g={x:0,y:g},i=Math.min,j=Math.max;this.__localToGlobal(e);this.__localToGlobal(h);this.__localToGlobal(f);this.__localToGlobal(g);b.__globalToLocal(e);b.__globalToLocal(h);b.__globalToLocal(f);b.__globalToLocal(g);a.left=i(e.x,h.x,f.x,g.x);a.right=j(e.x,h.x,f.x,g.x);a.top=i(e.y,h.y,f.y,g.y);for(a.bottom=j(e.y,h.y,f.y,g.y);d--;)e=c[d].__getBounds(b),e!==null&&a.__union(e);return a}}()}}}());switch(arguments.length){case 0:break;
case 1:typeof arguments[0]==="function"?(arguments[0].call(l),j=void 0):l.element=j;break;case 2:if(j)l.element=j;break;default:throw new SyntaxError("[object ElementNode](element, id): Invalid number of parameters.");}return l};a={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object ElementNode]"}}}})();doodle.ElementNode.isElementNode=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object ElementNode]")return!0;else a=Object.getPrototypeOf(a);return!1};
(function(){var a,f=0,d=doodle.utils.set_element_property;doodle.Layer=doodle.createLayer=function(c,e){var b=typeof c==="string"?c:"layer"+String("00"+f).slice(-2),b=Object.create(doodle.createElementNode(void 0,b));Object.defineProperties(b,a);Object.defineProperties(b,function(){var a=0,b=0,c=null,e=null;return{width:{enumerable:!0,configurable:!0,get:function(){return a},set:function(b){a=d(this.element,"width",b,"html")}},height:{enumerable:!0,configurable:!0,get:function(){return b},set:function(a){b=
d(this.element,"height",a,"html")}},context:{enumerable:!0,configurable:!0,get:function(){return e}},filters:{enumerable:!0,configurable:!0,get:function(){return c},set:function(a){c=a}},__addDomElement:{enumerable:!1,writable:!1,value:function(a){d(a,"position","absolute");if(this.parent)this.width=this.parent.width,this.height=this.parent.height;e=a.getContext("2d")}},__removeDomElement:{enumerable:!1,writable:!1,value:function(){e=null}}}}());switch(arguments.length){case 0:break;case 1:typeof arguments[0]===
"function"&&(arguments[0].call(b),c=void 0);break;case 2:b.element=e;break;default:throw new SyntaxError("[object Layer](id, element): Invalid number of parameters.");}if(b.element===null)b.element=document.createElement("canvas");f+=1;return b};a={toString:{enumerable:!0,writable:!1,configurable:!1,value:function(){return"[object Layer]"}},__getBounds:{enumerable:!0,configurable:!0,value:function(){var a=doodle.geom.createRectangle(0,0,0,0);return function(){return a.compose(0,0,this.width,this.height)}}()}}})();
doodle.Layer.isLayer=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object Layer]")return!0;else a=Object.getPrototypeOf(a);return!1};
(function(){var a,f=0,d,c,e,b,g,k,j,h=doodle.utils.create_scene_path,l=doodle.utils.get_element,n=doodle.utils.get_element_property,m=doodle.utils.set_element_property,o=doodle.createLayer,u=doodle.events.createEvent(doodle.events.Event.ANIMATION_FRAME),p=doodle.events.createMouseEvent(""),v=doodle.events.createKeyboardEvent("");doodle.Display=doodle.createDisplay=function(c){var e,t,i=typeof arguments[arguments.length-1]==="object"?Array.prototype.pop.call(arguments):{},q=1;c&&typeof c!=="function"&&
(c=l(c),t=n(c,"id"));t=typeof t==="string"?t:"display"+String("00"+f++).slice(-2);e=Object.create(doodle.createElementNode(void 0,t));Object.defineProperties(e,a);Object.defineProperties(e,function(){function a(b){S(b,L,B,B.length,G,H,D)}function c(a){var b,d;G=b=K?a.offsetX:a.clientX-s.offsetLeft;H=d=K?a.offsetY:a.clientY-s.offsetTop;T(a,L,B,B.length,b,d,D)}function f(a){U(a,L,B,o,o.length,D)}function i(a){V(a,Y,D)}function l(){W(o,o.length,J,J.length,X,B,B.length,D)}var q=0,t=0,s=null,o=e.children,
J=doodle.Emitter.emitter_queue,B=[],G=0,H=0,K=document.createEvent("MouseEvent").offsetX!==void 0,D=e,S=b,T=g,U=k,V=j,W=d,X=u,L=p,Y=v;document.addEventListener(doodle.events.KeyboardEvent.KEY_PRESS,i,!1);document.addEventListener(doodle.events.KeyboardEvent.KEY_DOWN,i,!1);document.addEventListener(doodle.events.KeyboardEvent.KEY_UP,i,!1);return{root:{enumerable:!0,writable:!1,configurable:!1,value:D},mouseX:{enumerable:!0,configurable:!1,get:function(){return G}},mouseY:{enumerable:!0,configurable:!1,
get:function(){return H}},width:{get:function(){return q},set:function(a){var b=o.length;m(this.element,"width",a+"px");for(q=a;b--;)o[b].width=a;return a}},height:{get:function(){return t},set:function(a){var b=o.length;m(this.element,"height",a+"px");for(t=a;b--;)o[b].height=a;return a}},activeLayer:{enumerable:!0,get:function(){return o[0]}},__addDomElement:{enumerable:!1,writable:!1,value:function(b){m(b,"position","relative");var d=n(b,"width","int")||b.width,e=n(b,"height","int")||b.height;
if(typeof d==="number")this.width=d;if(typeof e==="number")this.height=e;b.addEventListener(doodle.events.MouseEvent.MOUSE_MOVE,c,!1);b.addEventListener(doodle.events.MouseEvent.MOUSE_OUT,f,!1);b.addEventListener(doodle.events.MouseEvent.CLICK,a,!1);b.addEventListener(doodle.events.MouseEvent.DOUBLE_CLICK,a,!1);b.addEventListener(doodle.events.MouseEvent.MOUSE_DOWN,a,!1);b.addEventListener(doodle.events.MouseEvent.MOUSE_UP,a,!1);b.addEventListener(doodle.events.MouseEvent.CONTEXT_MENU,a,!1);b.addEventListener(doodle.events.MouseEvent.MOUSE_WHEEL,
a,!1);s=b}},__removeDomElement:{enumerable:!1,writable:!1,value:function(b){b.removeEventListener(doodle.events.MouseEvent.MOUSE_MOVE,c,!1);b.removeEventListener(doodle.events.MouseEvent.MOUSE_OUT,f,!1);b.removeEventListener(doodle.events.MouseEvent.CLICK,a,!1);b.removeEventListener(doodle.events.MouseEvent.DOUBLE_CLICK,a,!1);b.removeEventListener(doodle.events.MouseEvent.MOUSE_DOWN,a,!1);b.removeEventListener(doodle.events.MouseEvent.MOUSE_UP,a,!1);b.removeEventListener(doodle.events.MouseEvent.CONTEXT_MENU,
a,!1);b.removeEventListener(doodle.events.MouseEvent.MOUSE_WHEEL,a,!1);s=null}},allChildren:{enumerable:!0,configurable:!1,get:function(){return B}},__sortAllChildren:{enumerable:!1,configurable:!1,value:function(){h(this,B,!0).reverse()}},getNodesUnderPoint:{enumerable:!0,configurable:!1,value:function(a){for(var b=[],c=B,d=c.length,e=a.x,a=a.y,f;d--;)f=c[d],f.__getBounds(this).contains(e,a)&&b.push(f);return b}},addChildAt:{enumerable:!0,configurable:!1,value:function(){var a=D.addChildAt;return function(b,
c){b.width=this.width;b.height=this.height;this.element.appendChild(b.element);return a.call(this,b,c)}}()},removeChildAt:{enumerable:!0,writable:!1,configurable:!1,value:function(){var a=D.removeChildAt;return function(b){this.element.removeChild(o[b].element);return a.call(this,b)}}()},swapChildrenAt:{enumerable:!0,writable:!1,configurable:!1,value:function(){var a=D.swapChildrenAt;return function(b,c){b>c?this.element.insertBefore(o[c].element,o[b].element):this.element.insertBefore(o[b].element,
o[c].element);return a.call(this,b,c)}}()},frameRate:function(){var a=!1,b;return{get:function(){return a},set:function(c){c===0||c===!1?(a=!1,b!==void 0&&window.clearInterval(b)):c!==a&&(b!==void 0&&window.clearInterval(b),b=window.setInterval(l,1E3/c),a=c)}}}()}}());switch(arguments.length){case 0:break;case 1:typeof arguments[0]==="function"?(arguments[0].call(c),c=void 0):e.element=c;break;default:throw new SyntaxError("[object Display](element): Invalid number of parameters.");}d(e.children,
e.children.length,doodle.Emitter.emitter_queue,doodle.Emitter.emitter_queue.length,u,e.allChildren,e.allChildren.length,e);if(i.width!==void 0)e.width=i.width;if(i.height!==void 0)e.height=i.height;if(i.backgroundColor!==void 0)e.backgroundColor=i.backgroundColor;if(i.clearBitmap!==void 0)e.clearBitmap=i.clearBitmap;if(i.layers!==void 0)q=i.layers;e.frameRate=i.frameRate!==void 0?i.frameRate:24;if(e.children.length===0)for(;q--;)e.createLayer();return e};a={parent:{enumerable:!0,writable:!1,configurable:!1,
value:null},layers:{enumerable:!0,configurable:!1,get:function(){return this.children}},toString:{enumerable:!1,writable:!1,configurable:!1,value:function(){return"[object Display]"}},createLayer:{value:function(){return this.addChild(o.apply(void 0,arguments))}},removeLayer:{value:function(a){return this.removeChildById(a)}},__getBounds:{enumerable:!1,configurable:!0,value:function(){var a=doodle.geom.createRectangle(0,0,0,0);return function(){return a.compose(0,0,this.width,this.height)}}()}};d=
function(){var a=0;return function(b,d,f,g,h,j,k,l){for(l.clearBitmap===!0&&c(b,d);g--;)f[g].allListeners.hasOwnProperty("animationFrame")&&f[g].handleEvent(h.__setTarget(f[g]));e(j,k);f=l.width;for(j=l.height;d--;)if(l=b[d],l.filters){g=l.filters;for(h=g.length;h--;)g[h].__applyFilter(l.context,0,0,f,j)}a++}}();c=function(a,b){for(var c,d;b--;)if(c=a[b],c.clearBitmap===!0)d=c.context,d.save(),d.setTransform(1,0,0,1,0,0),d.clearRect(0,0,c.width,c.height),d.restore()};e=function(a){for(var b,c,d=a.length,
e,f,g,h=1;h<d;h++)if(c=b=a[h],(e=b.context)&&b.visible){g=!0;for(f=1;c;){if(!c.visible){g=!1;break}f*=c.alpha;c=c.parent}if(g)e.save(),e.globalAlpha=f,e.transform.apply(e,b.__allTransforms.__toArray()),typeof b.__draw==="function"&&b.__draw(e),e.restore()}};b=function(a,b,c,d,e,f,g){for(;d--;)if(c[d].__getBounds(g).contains(e,f))return c[d].emit(b.__copyMouseEventProperties(a,null)),!0;return!1};g=function(a,b,c,d,e,f,g){for(var h;d--;)if(h=c[d],h.__getBounds(g).contains(e,f)){if(!h.__pointInBounds)return h.__pointInBounds=
!0,h.emit(b.__copyMouseEventProperties(a,null,"mouseover")),h.emit(b.__copyMouseEventProperties(a,null,"mouseenter")),!0;h.emit(b.__copyMouseEventProperties(a,null));return!0}else if(h.__pointInBounds)return h.__pointInBounds=!1,h.emit(b.__copyMouseEventProperties(a,null,"mouseout")),h.emit(b.__copyMouseEventProperties(a,null,"mouseleave")),!0};k=function(a,b,c,d,e,f){if(e===0)f.__pointInBounds=!1;else{f=d[e-1];for(e=c.length;e--;)c[e].__pointInBounds=!1}f.emit(b.__copyMouseEventProperties(a,null,
"mouseout"));f.emit(b.__copyMouseEventProperties(a,null,"mouseleave"));return!0};j=function(a,b,c){c.broadcast(b.__copyKeyboardEventProperties(a,null));return!0}})();doodle.Display.isDisplay=function(a){if(typeof a==="object")for(;a;)if(a.toString()==="[object Display]")return!0;else a=Object.getPrototypeOf(a);return!1};
Object.defineProperty(doodle,"FontStyle",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{NORMAL:{enumerable:!0,writable:!1,configurable:!1,value:"normal"},ITALIC:{enumerable:!0,writable:!1,configurable:!1,value:"italic"},OBLIQUE:{enumerable:!0,writable:!1,configurable:!1,value:"oblique"}})});
Object.defineProperty(doodle,"FontVariant",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{NORMAL:{enumerable:!0,writable:!1,configurable:!1,value:"normal"},SMALL_CAPS:{enumerable:!0,writable:!1,configurable:!1,value:"small-caps"}})});
Object.defineProperty(doodle,"FontWeight",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{NORMAL:{enumerable:!0,writable:!1,configurable:!1,value:"normal"},BOLD:{enumerable:!0,writable:!1,configurable:!1,value:"bold"},BOLDER:{enumerable:!0,writable:!1,configurable:!1,value:"bolder"},LIGHTER:{enumerable:!0,writable:!1,configurable:!1,value:"lighter"}})});
Object.defineProperty(doodle,"TextAlign",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{START:{enumerable:!0,writable:!1,configurable:!1,value:"start"},END:{enumerable:!0,writable:!1,configurable:!1,value:"end"},LEFT:{enumerable:!0,writable:!1,configurable:!1,value:"left"},RIGHT:{enumerable:!0,writable:!1,configurable:!1,value:"right"},CENTER:{enumerable:!0,writable:!1,configurable:!1,value:"center"}})});
Object.defineProperty(doodle,"TextBaseline",{enumerable:!0,writable:!1,configurable:!1,value:Object.create(null,{TOP:{enumerable:!0,writable:!1,configurable:!1,value:"top"},MIDDLE:{enumerable:!0,writable:!1,configurable:!1,value:"middle"},BOTTOM:{enumerable:!0,writable:!1,configurable:!1,value:"bottom"},HANGING:{enumerable:!0,writable:!1,configurable:!1,value:"hanging"},ALPHABETIC:{enumerable:!0,writable:!1,configurable:!1,value:"alphabetic"},IDEOGRAPHIC:{enumerable:!0,writable:!1,configurable:!1,
value:"ideographic"}})});
(function(){var a,f=doodle.utils.hex_to_rgb_str,d=doodle.FontStyle,c=doodle.FontVariant,e=doodle.FontWeight,b=doodle.TextAlign,g=doodle.TextBaseline;doodle.Text=doodle.createText=function(k){var j=Object.create(doodle.createSprite());Object.defineProperties(j,a);Object.defineProperties(j,function(){function a(){var c=j.context||document.createElement("canvas").getContext("2d"),d,e,f=j.graphics,h=0,A=0,C=0;c.save();c.font=u+" "+p+" "+v+" "+m+"px "+n;d=c.measureText(k).width;e=m;o=c.measureText("m").width;
c.restore();j.graphics.clear();j.graphics.draw(function(a){if(x)a.fillStyle=x,a.fillRect(0,0,d,e);a.lineWidth=q;a.textAlign=s;a.textBaseline=r;a.font=u+" "+p+" "+v+" "+m+"px "+n;if(t)a.fillStyle=t,a.fillText(k,0,0);if(i)a.strokeStyle=i,a.strokeText(k,0,0)});j.width=d;j.height=e;switch(r){case g.TOP:A=m-o;C=m;break;case g.MIDDLE:A=-o/2;C=o/2;break;case g.BOTTOM:A=-m;break;case g.HANGING:A=m-o;C=m;break;case g.ALPHABETIC:A=-o;break;case g.IDEOGRAPHIC:A=-m}switch(s){case b.END:h=-d;break;case b.RIGHT:h=
-d;break;case b.CENTER:h=-d/2}f.__minX=h;f.__maxX=0;f.__minY=A;f.__maxY=C}var k="",n="sans-serif",m=10,o=m,u=d.NORMAL,p=c.NORMAL,v=e.NORMAL,s=b.START,r=g.ALPHABETIC,t="#000000",i="#000000",q=1,x;return{text:{enumerable:!0,configurable:!1,get:function(){return k},set:function(b){k=b;a()}},font:{enumerable:!0,configurable:!1,get:function(){return u+" "+p+" "+v+" "+m+"px "+n},set:function(a){var b,a=a.split(" ");b=a.length;b===2?a.unshift(d.NORMAL,c.NORMAL,e.NORMAL):b===3?a.splice(1,0,c.NORMAL,e.NORMAL):
b===4&&a.splice(1,0,c.NORMAL);j.fontStyle=a[0];j.fontVariant=a[1];j.fontWeight=a[2];j.fontSize=a[3];j.fontFamily=a[4]}},fontFamily:{enumerable:!0,configurable:!1,get:function(){return n},set:function(b){n=b;a()}},fontSize:{enumerable:!0,configurable:!1,get:function(){return m},set:function(b){typeof b==="string"&&(b=window.parseInt(b,10));m=b;a()}},fontStyle:{enumerable:!0,configurable:!1,get:function(){return u},set:function(b){u=b;a()}},fontVariant:{enumerable:!0,configurable:!1,get:function(){return p},
set:function(b){p=b;a()}},fontWeight:{enumerable:!0,configurable:!1,get:function(){return v},set:function(b){v=b;a()}},align:{enumerable:!0,configurable:!1,get:function(){return s},set:function(b){s=b;a()}},baseline:{enumerable:!0,configurable:!1,get:function(){return r},set:function(b){r=b;a()}},strokeWidth:{enumerable:!0,configurable:!1,get:function(){return q},set:function(a){q=a}},color:{enumerable:!0,configurable:!1,get:function(){return t},set:function(a){typeof a==="number"&&(a=f(a));t=a}},
strokeColor:{enumerable:!0,configurable:!1,get:function(){return i},set:function(a){typeof a==="number"&&(a=f(a));i=a}},backgroundColor:{enumerable:!0,configurable:!1,get:function(){return x},set:function(a){typeof a==="number"&&(a=f(a));x=a}}}}());switch(arguments.length){case 1:typeof arguments[0]==="function"?(arguments[0].call(j),k=void 0):j.text=k}return j};a={toString:{enumerable:!1,writable:!1,configurable:!1,value:function(){return"[object Text]"}}}})();
(function(){var a,f=doodle.utils.get_element,d=doodle.events.createEvent,c=doodle.events.Event.LOAD,e=doodle.events.Event.CHANGE;doodle.Image=doodle.createImage=function(b){var g=Object.create(doodle.createSprite());Object.defineProperties(g,a);Object.defineProperties(g,function(){function a(b){l=b;if(l.id!=="")g.id=l.id;g.width=l.width;g.height=l.height;g.graphics.draw(function(a){a.drawImage(l,0,0)});g.emit(d(c))}function b(){l!==null&&(l=null,g.graphics.clear(),g.emit(d(e)))}function h(b){var c=
f(b);if(typeof b==="string")g.id=b;c.complete?a(c):(c.onload=function(){a(c)},c.onerror=function(){throw new URIError("[object Image](imageSrc): Unable to load "+c.src);},c.onabort=function(){throw new URIError("[object Image](imageSrc): Unable to load "+c.src);})}var l=null;return{element:{enumerable:!0,configurable:!1,get:function(){return l},set:function(a){a===null||a===!1?b():h(a)}},src:{enumerable:!0,configurable:!1,get:function(){return l===null?null:l.src},set:function(a){if(a===null||a===
!1)b();else{var c=new window.Image;c.src=window.encodeURI(a);h(c)}}}}}());switch(arguments.length){case 1:typeof arguments[0]==="function"?(arguments[0].call(g),b=void 0):typeof b!=="string"?g.element=b:typeof b==="string"&&b[0]==="#"?g.element=b:g.src=b}return g};a={toString:{enumerable:!1,writable:!1,configurable:!1,value:function(){return"[object Image]"}}}})();

