name: axe
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  axe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Start Application
        run: npm start &
      - name: Wait for Application to Start
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
          entryPoint: 'http://localhost:4010'
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:4010 --exit
