name: axe
on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop
jobs:
  axe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:4010
      - name: Run axe
        run: |
          echo "Running axe-core accessibility checks..."
          npm install -g @axe-core/cli
          axe http://localhost:4010 --exit
