name: lighthouse
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install -g http-server
      - run: npm run build --if-present
      - run: http-server -s &
      - name: Run Lighthouse
        run: |
          npm install -g lhci/cli@0.7.x
          sleep 90
          lhci autorun
