name: pa11y
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  pa11y:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install -g http-server
      - run: npm run build --if-present
      - run: http-server -s &
      - name: Run Pa11y
        run: |
          npm install -g pa11y
          sleep 90
          pa11y http://127.0.0.1:8080
